deploy/artifacts/release.ts

- Releases are named for commit hash; actually include build artifacts (#112)
- Use SHA for release artifacts (#113)
- create synthetic tag name for releases (#115)
- try to use bazel node_modules for builds (#114)
- fix releases (#116)
- try to make bazelisk work again (#117)
- rootpath (#118)
- Mime (#119)
- use await to ensure we wait for asset upload

ensure wait for assets

---

deploy/artifacts/release.ts

- Releases are named for commit hash; actually include build artifacts (#112)
- Use SHA for release artifacts (#113)
- create synthetic tag name for releases (#115)
- try to use bazel node_modules for builds (#114)
- fix releases (#116)
- try to make bazelisk work again (#117)
- rootpath (#118)
- Mime (#119)
- use await to ensure we wait for asset upload
- fix upload issue due to https://github.com/octokit/octokit.js/discussions/2087\#discussioncomment-646569

fix upload issue due to https://github.com/octokit/octokit.js/discussions/2087#discussioncomment-646569

---

.github/workflows/ci.yml

- yarn fix (#122)
- use integrated CI, and automerge dependabot complaints (#123)
- tidy up the root dir a bit by moving jest out to its own folder (#124)
- move go formatting tools into go/fmt (#126)
- Change workflow name to 'ci' (#129)
- Move tools/bazel into bzl/ (#128)
- Cache bazel

bazel cache

---

.github/workflows/ci.yml

Concurrency key was empty on push (due to head-ref?)

Attempt fix deploy

---

.github/workflows/auto-update.yml

- remember to include release message https://github.com/Zemnmez/monorepo/runs/6906627705\?check_suite_focus\=true
- fixes
- Fix issue with deploy:
- Bump @bazel/bazelisk from 1.11.0 to 1.12.0
- Bump aws-sdk from 2.1154.0 to 2.1155.0
- Bump electron-to-chromium from 1.4.155 to 1.4.157
- Bump caniuse-lite from 1.0.30001352 to 1.0.30001354
- Bump @types/node from 17.0.43 to 18.0.0
- Bump esbuild from 0.14.43 to 0.14.44
- Bump @actions/core from 1.8.2 to 1.9.0
- Only bother committing if we actually made any changes https://github.com/Zemnmez/monorepo/runs/6909169682?check_suite_focus=true
- Add auto-update workflow

auto update

---

.github/workflows/ci.yml
deploy/BUILD
deploy/release.ts
js/npm/BUILD
js/npm/package_json/rules.bzl
js/npm/rules.bzl
ts/cmd/svgshot/BUILD

- remember to include release message https://github.com/Zemnmez/monorepo/runs/6906627705\?check_suite_focus\=true
- fixes
- Fix issue with deploy:
- Bump @bazel/bazelisk from 1.11.0 to 1.12.0
- Bump aws-sdk from 2.1154.0 to 2.1155.0
- Bump electron-to-chromium from 1.4.155 to 1.4.157
- Bump caniuse-lite from 1.0.30001352 to 1.0.30001354
- Bump @types/node from 17.0.43 to 18.0.0
- Bump esbuild from 0.14.43 to 0.14.44
- Bump @actions/core from 1.8.2 to 1.9.0
- move npm rules into npm folder

push versions

---

go/cmd/csvpretty/README.md

- Upgrade rules_nodejs for amd64
- Remove direct esbuild dep
- Remove need for weird directory hack
- Remove pulumi (for now). It's shit anyway
- Allow amd64
- Run fixers and modify to work on systems with no 'realpath'
- note on readlink
- attempt to fix rootDirs
- use swc
- upgrade some bazel deps
- use swc
- just kill me
- kill me
- still not working
- oops
- nothing is sticking
- new bazel
- remove swc
- actually comment these out correctly
- Bump @types/jest from 28.1.4 to 28.1.5
- add logic to minimize extraneous stuff from lockfiles
- fix csvpretty install instructions

fix csvpretty install instructions

---

deploy/program.ts

- use ts_project directly for pulumi
- more pulumi stuff
- pulumi success :)
- amend
- Bump esbuild-css-modules-plugin from 2.5.1 to 2.5.2
- Bump caniuse-lite from 1.0.30001377 to 1.0.30001378
- Bump date-fns from 2.29.1 to 2.29.2
- Bump electron-to-chromium from 1.4.222 to 1.4.225
- Bump aws-sdk from 2.1196.0 to 2.1198.0
- Bump setuptools from 65.0.1 to 65.1.0
- Bump @microsoft/api-extractor from 7.29.2 to 7.29.3
- Bump @microsoft/api-documenter from 7.19.4 to 7.19.5
- Ensure all exec'd files exist in dry run.

fix exec checks

---

.github/workflows/versioning.yml

The test cycle was being cancelled by the fact that versioning does not
run on main. This then also cancelled the automatic deploy.

Attempt fix for automatic deploys.

---

deploy/program.ts

- suspend github auth failure until execution of the release function. This ensures that the releasers can individually run and fail.
- fix
- Bump @typescript-eslint/parser from 5.35.1 to 5.36.1
- Bump caniuse-lite from 1.0.30001384 to 1.0.30001385
- Bump electron-to-chromium from 1.4.234 to 1.4.237
- Bump aws-sdk from 2.1205.0 to 2.1206.0
- Bump @fortawesome/fontawesome-svg-core from 6.1.2 to 6.2.0
- Bump @microsoft/api-documenter from 7.19.7 to 7.19.9
- Bump @types/react from 18.0.17 to 18.0.18
- Bump @typescript-eslint/eslint-plugin from 5.36.0 to 5.36.1
- Bump @fortawesome/free-solid-svg-icons from 6.1.2 to 6.2.0
- test for incorrect npm package name

test for incorrect package name

---

renovate.json

I'm in a predicament where my PAT means 'zemnmez' made most of the PRs. If I close them, Renovate thinks I don't want them merged; and if I open them, Renovate thinks someone else edited them. This should force renovate to re-open its own PRs for these.
If this doesn't work, I can add it to packageRules.

force renovate to make PRs even where they were closed

---

ts/next.js/rules.bzl

Next.js was silently choking on anything else, making files that
obviously cant work due to /

Just use git refs for next.js versions

---

js/npm/package_json/BUILD.bazel
js/npm/package_json/gen_pkgjson.ts
package.json
yarn.lock

- Bump @schemastore/package from 0.0.6 to 0.0.8
- fix issue introduced in 38e5880eddb58991154069e64fee8e1c02e93615

fix schemastore package

---

bzl/deps.bzl
js/npm/rules.bzl

- Update dependency aspect_rules_js to v1.27.0
- remove old publication code (which is replaced by aspect_rules_js

aspect rules js update

---

ts/fs/index.ts

This makes the fake root duck typed. The type of the fakeroot was breaking a couple of patch integrations like https://github.com/Zemnmez/monorepo/pull/3143.
I tried a fix in https://github.com/Zemnmez/monorepo/pull/3145, but it seems to have weird effects on the node exection environment, I'm guessing due to a bad lockfile change.

Minor refactor of ts/fs/index.ts

---

renovate.json

https://docs.renovatebot.com/configuration-options/#rollbackprs

Enable renovate rollback PRs (for if upstream makes a versioning mistake).

---

ts/pulumi/im/shadwell/thomas/public/index.ts
ts/pulumi/me/zemn/staging/index.ts

Fix asset paths for pulumi.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3179).
* #3180
* __->__ #3179

Fix asset paths for pulumi.

---

.bazel_fix_commands.json

Use npm run instead of yarn run in .bazel_fix_commands.json.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3206).
* #3207
* __->__ #3206

Use npm run instead of yarn run in .bazel_fix_commands.json.

---

bin/linux/pulumi/BUILD.bazel

Amend bin/linux/pulumi to correctly resolve under Windows.

Amend bin/linux/pulumi to correctly resolve under Windows.

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml

Remove now vestigial 'autoremove' job from .github/workflows/ci.yml
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3338).
* __->__ #3338
* #3339

Remove now vestigial 'autoremove' job from .github/workflows/ci.yml

---

bzl/run_in_workspace/BUILD.bazel
bzl/run_in_workspace/README.md
bzl/run_in_workspace/rules.bzl
bzl/run_in_workspace/wrapper.template.sh

Add bzl/run_in_workspace rule, which allows a binary to be run in the dev's workspace.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3357).
* #3358
* __->__ #3357

Add bzl/run_in_workspace rule, which allows a binary to be run in the dev's workspace.

---

js/eslint/rules.bzl
ts/rules.bzl

eslint_test to depend directly on //:tsconfig (it won't run without it anyway!)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3427).
* #3431
* #3430
* #3429
* #3428
* __->__ #3427

eslint_test to depend directly on //:tsconfig (it won't run without it anyway!)

---

.github/workflows/ci.yml

Perform presubmit after push so that PRs can pick up the cache artifacts.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3523).
* __->__ #3523
* #3522

Perform presubmit after push so that PRs can pick up the cache artifacts.

---

ts/next.js/index.tsx

Fix production CSP defined in ts/next.js/index.tsx
One day this will need proper testing so that we don't just get errors like this in production!

Fix production CSP defined in ts/next.js/index.tsx

---

.github/workflows/ci.yml

Back out "Use https://github.com/easimon/maximize-build-space in github actions runners to increase disk space."
It was causing jobs to simply time out, and for mysterious reasons this would cause a merge.
Original commit changeset: 8943597a8ad0

Back out "Use https://github.com/easimon/maximize-build-space in github actions runners to increase disk space."

---

ts/pulumi/index.ts
ts/pulumi/lib/website.ts
ts/pulumi/pleaseintroducemetoyour.dog/index.ts
ts/pulumi/shadwell.im/index.ts
ts/pulumi/zemn.me/index.ts

Back out "Implement noIndex for staging builds."
For reasons currently unknown -- if a test returns a neutral status then automerge still merges!
As a result, the pulumi code here fails and yet the merge still happened.
Original commit changeset: c37300567dc9
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3539).
* #3540
* __->__ #3539

Back out "Implement noIndex for staging builds."

---

ts/pulumi/index.ts
ts/pulumi/lib/website.ts
ts/pulumi/pleaseintroducemetoyour.dog/index.ts
ts/pulumi/shadwell.im/index.ts
ts/pulumi/zemn.me/index.ts

Roll forward "Implement noIndex for staging builds."
Testing weirdness means neutral tests get merged. I am unsure why.
Original commit changeset: e9426a254f68

Roll forward "Implement noIndex for staging builds."

---

ts/pulumi/index.ts
ts/pulumi/lib/website.ts
ts/pulumi/pleaseintroducemetoyour.dog/index.ts
ts/pulumi/shadwell.im/index.ts
ts/pulumi/zemn.me/index.ts

Back out "Roll forward "Implement noIndex for staging builds.""
Need to set some basic headers in the base config so that they work on production as well as staging.
```
* creating CloudFront Response Headers Policy (monorepo_shadwell-im_thomas_shadwell_im_website_response_headers-e78b2ae): InvalidArgument: The parameter Response Headers Config  requires atleast one of CORS, Security Headers, Remove Headers, Server Timing Headers or Custom Headers.
```
Original commit changeset: 9e1401cde9e4
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3544).
* #3333
* #3332
* #3301
* #3300
* #3298
* #3297
* #3547
* #3545
* __->__ #3544

Back out "Roll forward "Implement noIndex for staging builds.""

---

ts/pulumi/index.ts
ts/pulumi/lib/website.ts
ts/pulumi/pleaseintroducemetoyour.dog/index.ts
ts/pulumi/shadwell.im/index.ts
ts/pulumi/zemn.me/index.ts

Implement noIndex for staging builds and security header policy builds for both production and staging builds.
Back out "Back out "Roll forward "Implement noIndex for staging builds."""
Original commit changeset: b08f969f85609cc7e1dbc8314eef8fbca060ad88
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3545).
* #3333
* #3332
* #3301
* #3300
* #3298
* #3297
* #3547
* __->__ #3545

Implement noIndex for staging builds and security header policy builds for both production and staging builds.

---

pnpm-lock.yaml
project/cultist/gen/collate_game_core.ts
project/cultist/multiplayer/index.tsx
project/cultist/react/table.tsx
project/zemn.me/elements/NavBar/NavBar.tsx
project/zemn.me/next/components/timeline/timeline.tsx
renovate.json
ts/do-sync/doSync.ts
ts/math/canvas/element.tsx
ts/math/shape/shape_test.tsx
ts/react/article/blurb/blurb_test.tsx
ts/react/article/blurb/index.tsx
ts/react/article/index.tsx
ts/react/element/link/link_test.tsx
ts/react/lang/index.tsx
ts/url/index.ts

Fix tests accidentally ephemerally introduced in c466cd3a1697b51b7b7436be2095b26372abf460 and cfb413f7a0eafd6b6cbae2351eba227c2d07c592.
Prevent renovate adding all JSON files as part of automatic fixing.
Based on this comment, renovate was adding some very strange files https://github.com/Zemnmez/monorepo/pull/3488#issuecomment-1666254625 -- and as a result, the diff did NOT include an update to pnpm.lock, resulting in the tests passing when, since the lockfile was not updated, the changes did not happen correctly.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3563).
* #3564
* __->__ #3563

Fix tests accidentally ephemerally introduced in c466cd3a1697b51b7b7436be2095b26372abf460 and cfb413f7a0eafd6b6cbae2351e

---

BUILD.bazel
ci/presubmit.ts
pnpm_lock_sync_test.sh

Amend pnpm_lock_sync_test to fail anytime pnpm is sad (not just if the lockfile is out of date)
Move pnpm test into presubmit (it breaks out of the sandbox)
Amend pnpm lock sync test accounting for upstream fix.
https://github.com/pnpm/pnpm/issues/6913#event-10016924188
Revert all changes to package.json since lockfile test was broken.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3606).
* #3603
* __->__ #3606

Amend pnpm_lock_sync_test to fail anytime pnpm is sad (not just if the lockfile is out of date)

---

ci/presubmit.ts
package.json

Back out "Update dependency @microsoft/api-documenter to v7.22.33"
Original commit changeset: c8a5b32cd752
The local bazel version of pnpm with --frozen-lockfile and --lockfile only is broken because it's out of date :/

Back out "Update dependency @microsoft/api-documenter to v7.22.33"

---

ts/pulumi/lib/certificate.ts
ts/pulumi/lib/website.ts

Make DNS records delete before replacement because they're unique.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3645).
* #3638
* #3636
* #3635
* __->__ #3645

Make DNS records delete before replacement because they're unique.

---

.npmrc

Set strict-peer-dependencies to true for pnpm.
strict-peer-dependencies is apparently always true for pnpm 7.x and above.
This thread: https://github.com/renovatebot/renovate/discussions/15416#discussioncomment-2678966
states that it could be the cause of the lockfile not updating issues I'm seeing -- but I don't see pnpm actually complaining about
any dependencies even with this enabled.

Set strict-peer-dependencies to true for pnpm.

---

.github/workflows/ci.yml
ci/presubmit.ts
ts/pulumi/deploy_to_staging.ts

Add --overwrite to presubmit (used to do a destroy() before pulumi up().
This commit includes a change to put the presubmit to pulumi in overwrite mode cause it's in a weird state.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3656).
* #3655
* #3654
* __->__ #3656

Add --overwrite to presubmit (used to do a destroy() before pulumi up().

---

.github/workflows/ci.yml
.github/workflows/codeql.yml

Deploy main to staging before trying to deploy the candidate branch.
This commit addresses a subtle, and fairly complex problem.
Pulumi does not know when two resources are mutually exclusive (e.g. DNS records in the same zone).
As a result, to correctly handle these cases, it must be made aware that these resources are the same via aliases.
However, a *failure* does not indicate a roll-back to a known good state -- meaning that under these conditions:
1. A mutually exclusive resource is deployed to the staging environment
2. That content is not destroyed
3. Another candidate branch attempts to deploy this mutually exclusive resource again
-- under these conditions, one candidate can fail due to a mistake in a previous test.
In order to thoroughly address this, we:
1. Destroy the Pulumi …

Deploy main to staging before trying to deploy the candidate branch.

---

ts/pulumi/lib/website.ts

Use FileAsset with website BucketObject upload -- this should invalidate old objects based on hash.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3661).
* #3662
* __->__ #3661

Use FileAsset with website BucketObject upload -- this should invalidate old objects based on hash.

---

project/zemn.me/next/components/timeline/timeline.module.css

zemn.me: alter timeline code not to prefer breaking where it's not needed.
Because the grid area was set to min-content, the browser text wrapping algorithm was eagerly breaking -- and since asian languates do not break between words, the algorithm would put one character of the word on each line when viewing the timeline from, for example, ja-JA locale.

zemn.me: alter timeline code not to prefer breaking where it's not needed.

---

project/zemn.me/next/pages/index.tsx

zemn.me: Fix typo "computersecurity" and disambiguate "security program"

zemn.me: Fix typo "computersecurity" and disambiguate "security program"

---

ts/pulumi/lib/website.ts

CloudFront distribution must be deleted before it is replaced since it may be trying to use CNAMEs that are associated with other resources:
Diagnostics:
aws:cloudfront:Distribution (monorepo_shadwell.im_thomas_shadwell_im_website_cloudfront_cloudfront_distribution):
error: 1 error occurred:
* creating CloudFront Distribution: CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.
status code: 409, request id: b8ca173c-a86e-4ec5-88aa-75dabf1b87d6
aws:cloudfront:Distribution (staging.zemn.me_cloudfront_cloudfront_distribution):
error: 1 error occurred:
* creating CloudFront Distribution: CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.
status code: 409, request id: …

CloudFront distribution must be deleted before it is replaced since it may be trying to use CNAMEs that are associated w

---

ts/pulumi/zemn.me/availability/pages/index.tsx

availability.zemn.me: add a direct link in case Google security checks fail.

availability.zemn.me: add a direct link in case Google security checks fail.

---

ts/pulumi/lib/website.ts

pulumi website: add s3:ListBucket permission so that 404s don't become 403s.

pulumi website: add s3:ListBucket permission so that 404s don't become 403s.

---

bzl/deps.bzl

Back out "Update dependency com_google_protobuf to v24" -- merged even though the tests didn't pass!
Original commit changeset: d17e75f2d6ed
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3720).
* #3719
* __->__ #3720

Back out "Update dependency com_google_protobuf to v24" -- merged even though the tests didn't pass!

---

ci/submit.ts

Attempted fix to pernicious refresh only issue.
It looks like the following was the case:
1. When Pulumi is not latest, pulumi prints that issue to stderr.
2. My code was interpreting that as an error, and throwing
3. This cancelled execution before stack.up() happened.

Attempted fix to pernicious refresh only issue.

---

ts/pulumi/lib/website.ts

Replace deprecated pulumi.aws.s3.BucketObject with pulumi.aws.s3.BucketObjectv2.

Replace deprecated pulumi.aws.s3.BucketObject with pulumi.aws.s3.BucketObjectv2.

---

ts/pulumi/lib/website.ts

All websites silently died because I replaced BucketObject with BucketObject V2. This should fix those issues.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3739).
* #3740
* __->__ #3739

All websites silently died because I replaced BucketObject with BucketObject V2. This should fix those issues.

---

ts/pulumi/lib/website.ts

pulumi website: remove deprecated 'websites' configuration parameter that is technically never used.

pulumi website: remove deprecated 'websites' configuration parameter that is technically never used.

---

ci/BUILD.bazel
ci/bazel.ts
ci/bazel_test.ts
ci/presubmit.ts
ts/github/actions/index.ts
ts/iter/async.ts

Some annotations for GitHub
ci: move data deps explicitly into the relevant binaries
This prevents building the entire project before passing over to the pre/postsubmit runner.

Some annotations for GitHub

---

.github/workflows/ci.yml

Perform staging actions only when onboarded to the merge queue.

Perform staging actions only when onboarded to the merge queue.

---

renovate.json

Try to get renovate to ignore bazel dist dir:
ERR_PNPM_JSON_PARSE Expected property name or '}' in JSON at position 2 while parsing '{' in /tmp/renovate/repos/github/zemn-me/monorepo/dist/monorepo/dist/monorepo/dist/monorepo/dist/monorepo/dist/monorepo/dist/monorepo/dist/monorepo/dist/monorepo/dist/monorepo/external/npm__resolve__1.22.2/package/test/resolver/malformed_package_json/package.json
1 | {
> 2 |
| ^

Try to get renovate to ignore bazel dist dir:

---

.github/workflows/renovate.yml

Prevent overlapping instances of renovate running.

Prevent overlapping instances of renovate running.

---

renovate.json

Delete bazel "dist" folder after post upgrade tasks to prevent pnpm getting confused.
https://github.com/zemn-me/monorepo/pull/3848#issuecomment-1784026554

Delete bazel "dist" folder after post upgrade tasks to prevent pnpm getting confused.

---

.github/workflows/ci.yml

Remove pull request presubmit concurrency limit.
Unfortunately, this appears to have caused a problem when interacting with sapling such that
sapling pushing an amended commit would just cause both the running task AND the task
at the new head being tested.
Removing this entirely means that both tests will be run -- but tests don't take that
long these days anyway.

Remove pull request presubmit concurrency limit.

---

js/eslint/private/BUILD.bazel
js/eslint/private/eslint.bzl

Move eslint data deps into a filegroup so that issues are correctly pinpointed by bazel.

Move eslint data deps into a filegroup so that issues are correctly pinpointed by bazel.

---

ts/pulumi/lib/website.ts

Back out "Add SPF record to Website.". This reverts commit: 781534737fa2a10b6dff8b93f902255f01062e26
In https://github.com/zemn-me/monorepo/pull/3963, I said this would probably fail, but it had skipped my mind that it would probably fail at submit time rather than staging time because the TXT records this collides with are defined directly in the AWS console, not in Pulumi.
I think the best solution to this in the long run would be to move the TXT records into 'Website' in ts/pulumi/lib via a new TXT field or something. Then I can have Website inject the SPF records for each Website. Issue for this: https://github.com/zemn-me/monorepo/issues/3964
Pulumi update error:
```
Diagnostics:
pulumi:pulumi:Stack (Zemnmez/monorepo-2/prod)
error: update failed
aws:route53:Record …
```

Back out "Add SPF record to Website.". This reverts commit: 781534737fa2a10b6dff8b93f902255f01062e26

---

project/zemn.me/next/pages/index.tsx

zemn.me: fix links not using the <Link/> element.
Fixes #3992
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/3996).
* #3991
* __->__ #3996

zemn.me: fix links not using the <Link/> element.

---

WORKSPACE

rules_python corrections necessitated in https://github.com/zemn-me/monorepo/pull/3852
- Remove register_toolchains which has not been needed since 0.23.0 https://github.com/bazelbuild/rules_python/releases/tag/0.23.0
- Add py_repositories which has been possible to omit before, but is mandatory since 0.26.0 https://github.com/bazelbuild/rules_python/releases/tag/0.26.0

rules_python corrections necessitated in https://github.com/zemn-me/monorepo/pull/3852

---

.github/workflows/ci.yml

Remove setup-chrome from the presubmit. The test it was used for has been disabled.

Remove setup-chrome from the presubmit. The test it was used for has been disabled.

---

renovate.json

Renovate: set rangeStrategy to "pin" as a workaround for https://github.com/renovatebot/renovate/issues/21438
See also: https://github.com/renovatebot/renovate/discussions/22133#discussioncomment-5886419

Renovate: set rangeStrategy to "pin" as a workaround for https://github.com/renovatebot/renovate/issues/21438

---

ts/cmd/svgshot/svgshot_test.ts

Back out "Accept SVGShot tests not passing for now."
I think it's possible that pinning the deps has fixed whatever issue we were experiencing here.
Original commit changeset: dfb28ef2c124

Back out "Accept SVGShot tests not passing for now."

---

project/zemn.me/bio/bio.ts

bio: correct OpenAI team name.

bio: correct OpenAI team name.

---

ci/bazel.ts

Fix issue whereby upon error, if we were listening to both 'exit' and 'close', the process would immediately terminate without issue.

Fix issue whereby upon error, if we were listening to both 'exit' and 'close', the process would immediately terminate w

---

project/zemn.me/next/pages/experiments/emoji/flag.tsx

https://zemn.me/experiments/emoji/flag: correct spelling of 'sovereignty'.

https://zemn.me/experiments/emoji/flag: correct spelling of 'sovereignty'.

---

.vscode/go.sh
.vscode/settings.json
.vscode/testing/BUILD.bazel
.vscode/testing/test_tools_run.sh

Have Go for vscode use the bazel workspace's version of go.

Have Go for vscode use the bazel workspace's version of go.

---

.vscode/go.sh
.vscode/settings.json

Hotfix .vscode/go.sh to run in the correct CWD

Hotfix .vscode/go.sh to run in the correct CWD

---

CODEOWNERS

Make @zemnmez the sole owner of the files that dependabot might change.
Because of https://github.com/orgs/community/discussions/9636, it's not possible
to have single-person aprovals for CODEOWNERS unless there is only one and
exactly one owner (and not a group).
This means by previously having these also owned by the bot, while intended
to have the bot self-approve for these changes it actually meant that
I, @zemnmez, had to bypass branch checks every single time or log
into a bot account to get approval.

Make @zemnmez the sole owner of the files that dependabot might change.

---

sh/bin/bazel
sh/bin/bazelisk
sh/run_bazel.sh

Add bazel / bazelisk to sh/bin and use bazelisk for all bazel commands.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4379).
* #4380
* __->__ #4379

Add bazel / bazelisk to sh/bin and use bazelisk for all bazel commands.

---

.github/workflows/ci.yml
ci/presubmit.ts

Add --tool_tag tracking to presubmit.
See: https://bazel.build/reference/command-line-reference#flag--tool_tag

Add --tool_tag tracking to presubmit.

---

.vscode/testing/BUILD.bazel
sh/bin/BUILD.bazel
sh/bin/dlv
sh/bin/go
sh/bin/goimports
sh/bin/gopackagesdriver
sh/bin/staticcheck

sh/bin: bazel alias for dlv, gopackagesdriver, staticcheck, goimports and go
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4436).
* #4425
* #4437
* __->__ #4436

sh/bin: bazel alias for dlv, gopackagesdriver, staticcheck, goimports and go

---

js/npm/package_json/BUILD.bazel
js/npm/package_json/gen_pkgjson.ts
ts/constants/constants.ts

Back out "Back out "js/npm/package_json/gen_pkgjson.ts: use the repo url constant""
Original commit changeset: 4b266c34675f

Back out "Back out "js/npm/package_json/gen_pkgjson.ts: use the repo url constant""

---

package.json
pnpm-lock.yaml
project/zemn.me/bio/bio.ts
project/zemn.me/bio/testing/BUILD.bazel
project/zemn.me/bio/testing/ensure_ids_unique_test.ts
project/zemn.me/components/BUILD.bazel
project/zemn.me/components/SectionLink/SectionLink.module.css
project/zemn.me/components/SectionLink/SectionLink.tsx
project/zemn.me/components/timeline/timeline.tsx
ts/react/lang/BUILD.bazel
ts/react/lang/index.tsx

project/zemn.me: introduce UUIDs for events for permalinks and utilize those permalinks in the site.
Minor changes included:
- package.json & pnpm-lock.yml: add memoizee & @types/memoizee
- project/zemn.me/bio/bio.ts: add the IDs
changed project/zemn.me/components/timeline/timeline.tsx:  add section marks and be more zealous about having full stops at the end of fragments and sentences.
- ts/react/lang/index.tsx: add a memoized getter for the Intl.locale of the lang
- project/zemn.me/components/SectionLink/...: a variant of the <Link> tag that has rel="bookmark" and uses smaller text.
- project/zemn.me/bio/testing/...: tests to ensure that there aren't duplicate IDs
Fixes https://github.com/zemn-me/monorepo/issues/4444

project/zemn.me: introduce UUIDs for events for permalinks and utilize those permalinks in the site.

---

ci/BUILD.bazel
ci/presubmit.ts

Back out "Back out "ci/presubmit: use local Go binary version to ensure syncronicity.""
Original commit changeset: 30360d4a74cd

Back out "Back out "ci/presubmit: use local Go binary version to ensure syncronicity.""

---

project/zemn.me/testing/browser_test.ts

Try to make the web tests less flakey by having the browser wait 1 second.

Try to make the web tests less flakey by having the browser wait 1 second.

---

.vscode/settings.json

VSCode should always autoformat source.

VSCode should always autoformat source.

---

ts/pulumi/zemn.me/voice/voice.ts

ConnectInstance to have unique instanceAlias name so that prod and staging don't conflict.

ConnectInstance to have unique instanceAlias name so that prod and staging don't conflict.

---

BUILD.bazel
WORKSPACE
fix_go_version_sync.sh
go/cmd/version_sync/BUILD.bazel
go/cmd/version_sync/main.go
go_version.bzl
renovate.json

Introduce scripts to keep go.mod Go version and bazel Go version in sync.

Introduce scripts to keep go.mod Go version and bazel Go version in sync.

---

.github/workflows/bootstrap_bazel_remote_cache.sh

Replace the deprecated --experimental_remote_build_event_upload with --build_event_upload

Replace the deprecated --experimental_remote_build_event_upload with --build_event_upload

---

go/fmt/BUILD.bazel
go/fmt/rules.bzl
go/fmt/test_fmt.sh
go/rules.bzl

Go_fmt format tests with aspect_rules_lint.
Needs https://github.com/aspect-build/rules_lint/pull/189 to have landed.

Go_fmt format tests with aspect_rules_lint.

---

.github/workflows/ci.yml

Fix CI for renovate branch automerging.
See: https://docs.renovatebot.com/key-concepts/automerge/#branch-vs-pr-automerging
I was getting:
Pending Branch Automerge
These updates await pending status checks before automerging. Click on a checkbox to abort the branch automerge, and create a PR instead.
chore(deps): pin dependencies (resolve, source-map-loader)
chore(deps): update dependency mime to v4.0.3
fix(deps): update dependency devtools-protocol to v0.0.1292262
fix(deps): update nextjs monorepo to v14.2.3 (@next/eslint-plugin-next, eslint-config-next)
chore(deps): update dependency @pulumi/awsx to v2.9.0
chore(deps): update dependency aspect_rules_lint to v0.19.0
chore(deps): update dependency renovate to v37.323.1

Fix CI for renovate branch automerging.

---

.github/workflows/ci.yml

Remove presubmit to removate branches now renovate branch merge is no longer a thing.

Remove presubmit to removate branches now renovate branch merge is no longer a thing.

---

BUILD.bazel

Lint hotfix: add package.json to runfiles for eslintrc so it can run in module mode.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/5475).
* #5472
* __->__ #5475

Lint hotfix: add package.json to runfiles for eslintrc so it can run in module mode.

---

BUILD.bazel
js/testing/node_version/node_version_test.ts
package.json
project/cultist/element_test.ts
project/linear2/features/elements/CodeBlock/index.tsx
project/linear2/features/elements/headingsAndSections/fancy.tsx
project/linear2/features/elements/headingsAndSections/headingsAndSections.tsx
project/linear2/features/elements/headingsAndSections/outlineState.tsx
project/linear2/features/elements/timeline/components.tsx
project/linear2/features/elements/util.test.ts
project/zemn.me/app/layout.tsx
ts/factorio/upgrade_planner.ts
ts/iter/index.ts
ts/jest/jest.browser.config.ts
ts/jest/jest.node.config.ts
ts/next.js/next.config.ts
ts/pulumi/pleaseintroducemetoyour.dog/app/daily/client.tsx
ts/react/PrettyJSON/pretty_json.tsx
ts/react/element/link/link_test.tsx
ts/react/lang/index.tsx

Hotfix: add @eslint/compat to eslint config
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/5476).
* #5472
* __->__ #5476

Hotfix: add @eslint/compat to eslint config

---

ts/factorio/blueprint_string.ts

factorio blueprint string: use parse and transform correctly.

factorio blueprint string: use parse and transform correctly.

---

package.json
pnpm-lock.yaml

Back out "chore(deps): update dependency @microsoft/api-extractor to v7.46.1"
Original commit changeset: 5516d5a5a76b

Back out "chore(deps): update dependency @microsoft/api-extractor to v7.46.1"

---

.vscode/settings.json

vscode eslint plugin to use flat format.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/5603).
* #5605
* #5604
* #5598
* #5597
* __->__ #5603

vscode eslint plugin to use flat format.

---

sh/bin/bazelisk

Speed up invocations of bazelisk (and thus all commands in sh/bin) by using the non-npx version if available.

Speed up invocations of bazelisk (and thus all commands in sh/bin) by using the non-npx version if available.

---

renovate.json

Renovate: add bazel and bazelisk to set using postUpgradeTasks so that it updates MODULE.bazel.lock.

Renovate: add bazel and bazelisk to set using postUpgradeTasks so that it updates MODULE.bazel.lock.

---

.github/workflows/sapling.yml

Remove "opened" and "syncronize" from sapling workflow; they don't

---

py/ci/postUpgrade/__main__.py
renovate.json

First seen broken in [pr6719].
[pr6719]: https://github.com/zemn-me/monorepo/pull/6719
`rules_rust` was causing the build to be broken if any rust crates
digests were wrong, even if no rust was involved in the build.
This was preventing the renovate postupgrade script from running,
since it is checked into the Bazel workspace.
Adding CARGO_BAZEL_REPIN=true to the bazelisk invocation fixes this,
as the repin happens during the run command. I then strip
that particular env for the Bazel subcommands to ensure that
we don't repin multiple times per run.
***
I reported this as an issue here: https://github.com/bazelbuild/rules_rust/issues/2915
---
* #6748
* __->__ #6747

Un-break renovate postupgrade for rust.

---

renovate.json

thus far i have not been able to fix renovate.
that said, the renovate base image claims to have bazelisk: https://github.com/containerbase/base/blob/483ab25f05e6bb6081503a246fab88cf890fc862/test/Dockerfile.distro#L48
so even though this won't improve the broken state, this will at least help me get toward working out why
ghe isn't seeing bazelisk.

just make renovate use bazelisk again.

---

sh/postUpgrade.sh

tell me this isn't some terrible ploy to destroy my mental health
Command failed: ./sh/postUpgrade.sh
cat: /home/ubuntu/.cache: No such file or directory
cat: /home/ubuntu/.cache/bazelisk: No such file or directory
2024/11/10 17:40:52 could not create directory /home/ubuntu/.cache/bazelisk: mkdir /home/ubuntu/.cache: file exists

I'm still fucking bewildered about what is broken here. check out the output from the last commit:
