.github/workflows/ci.yml

Run and cache tests on merge; remove concurrency restriction

---

ts/cmd/svgshot/svgshot_test.ts

- Specify deps for css lint
- fix svgshot (#258)
- update react (#248)
- Increase svgshot timeout

increase svgshot timeout

---

.github/versioning/versioning.md
.github/workflows/ci.yml
bzl/versioning/rules.bzl

- Basic versioning code
- Try to make the automatic commit system work
- Remove useless file
- Extra rules
- oopsie

version pipelining

---

package.json
project/cultist/react/table.tsx
yarn.lock

- merge some bash into the main workflow; skip making a PR (github doesn't actually run the tests anyway :()
- inline more bash stuff
- do not fail CI on expected errors.
- try to see what's causing failures
- Bump typescript from 4.6.4 to 4.7.3
- upgrade typescript

upgrade typescript

---

.github/workflows/ci.yml

- trigger workflows on versioned branch too
- add versioning to package.json, and export svgshot
- Fix visibility and other issues
- add README.md to svgshot
- automatic fixes
- Fix github token not being set https://github.com/Zemnmez/monorepo/runs/6873294141?check_suite_focus=true

fix auto merge github token

---

.github/workflows/ci.yml

- remember to include release message https://github.com/Zemnmez/monorepo/runs/6906627705\?check_suite_focus\=true
- fixes
- Fix issue with deploy:

fix version deploy

---

.github/workflows/versioning.yml

- blah
- add APDU impl
- add instruction generation
- hell
- generate a bunch of bs
- add some CSVs and some tools to tidy them
- idk
- better generation
- refactor generation into command
- p close to being done with generated gode
- extract csvpretty from cardauth project
- test and readme
- Create LICENSE
- readme.md
- remove lines which were as annoying as they were cool
- installation and usage
- fix go.mod, add to readme.md
- Move csvpretty files in preparation for merge
- Move csvpretty into go
- build file
- run fixers
- integration test for csvpretty
- Update versioning.yml
- Bump update-browserslist-db from 1.0.3 to 1.0.4
- Bump eslint-plugin-react from 7.30.0 to 7.30.1
- Bump aws-sdk from 2.1160.0 to 2.1161.0
- Bump electron-to-chromium from 1.4.167 to 1.4.168
- Bump …

version management

---

.github/workflows/auto-update.yml

- upgrade rules_python
- remove dep on yaml-validator
- add to dependabot
- just avoid all these automatic update shenanigans
- Revert "just avoid all these automatic update shenanigans"
- fix github-token position
- yaml test runner executable
- make auto-update use the GH_PAT to allow actions cycles

disable auto update

---

deploy/BUILD
deploy/deploy_test.ts
deploy/program.ts
js/npm/rules.bzl
ts/do-sync/testing/BUILD

- allow publishes to fail
- more accurate fix detection
- failing publishes are okay, and don't cause other operations to also fail
- more testing

failing publish okay

---

js/npm/rules.bzl
ts/cmd/svgshot/BUILD
ts/cmd/svgshot/README.md

Remove docs from the npm package. At some point, I'll have to work out where to put these.

Exclude docs from npm pkg. At some point, I'll need to work out how to surface them.

---

ts/cmd/svgshot/BUILD

add README.md back to svgshot

---

js/npm/package_json/gen_pkgjson.ts
ts/knowitwhenyouseeit/package.template.json

Version should not be specified in package template.

---

deploy/BUILD
deploy/deploy_test.ts
deploy/program.ts
package.json

- make yarn dev scoped
- do not allow dry runs of deploy to fail

fix exec checks

---

.github/workflows/ci.yml
.github/workflows/deployment.yml

- Ensure we await for all promises. Don't force exit.
- remove settings overridden by .editorconfig
- make it such that deployments are not cancelled by integration testing

versioned deploy

---

js/npm/package_json/gen_pkgjson.ts
js/npm/package_json/rules.bzl
ts/cmd/svgshot/package.template.json
ts/do-sync/package.template.json
ts/knowitwhenyouseeit/package.template.json

- Generate more package.json stuff
- fixes

package json generation

---

rs/ts/BUILD.bazel
rs/ts/index.rs

- 
- Add a draft of rs/ts, a typescript serializer.
-

css module support rust

---

rs/rules.bzl
rs/ts/index.rs

- //rs: centralise rust rules to //rs:rules.bzl
- Rust formatting / linting tests.
- 
- Implement rust clippy tests
-

rust clippy

---

bzl/deps.bzl

This reverts commit 0048b7fa9de103ad9c02f8d8cf20ebf062f0ef62.

Revert "Update dependency pulumi_cli to v3.47.0"

---

bin/linux/pulumi/BUILD.bazel
bin/linux/pulumi/smoke.sh

- Revert "Update dependency pulumi_cli to v3.47.0"
- smoke test for pulumi

revert pulumi cli bump

---

.github/workflows/renovate.yml
renovate.json

Use self-hosted renovate.

---

project/zemn.me/bio/bio.ts
project/zemn.me/elements/TimeEye/BUILD.bazel
ts/next.js/index.tsx
ts/pulumi/me/zemn/staging/public/BUILD.bazel
ts/pulumi/me/zemn/staging/public/pages/_app.tsx
ts/pulumi/me/zemn/staging/public/pages/index.tsx

- fix next dev headers
- demonstrate efficacy of staging

zemn me staging

---

package.json
pnpm-lock.yaml

Amend package.json scripts with lots of -- to allow pnpm to run.
This is because of all the commands in commands going on here.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3169).
* #3170
* __->__ #3169

Amend package.json scripts with lots of -- to allow pnpm to run.

---

.github/workflows/ci.yml
.github/workflows/deployment.yml

update bazel cache scheme to match upstream example

update bazel cache scheme to match upstream example

---

deploy/BUILD.bazel

Add package.json to data bundle for deploy (it was complaining it couldn't see it).

Add package.json to data bundle for deploy (it was complaining it couldn't see it).

---

.bazel_fix_commands.json

remove old project_deps code.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3207).
* __->__ #3207
* #3206

remove old project_deps code.

---

ts/guard.ts

Add extra 'message' parameter to 'guard.must' (2).
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3208).
* #3205
* #3180
* __->__ #3208

Add extra 'message' parameter to 'guard.must' (2).

---

project/zemn.me/elements/TimeEye/TimeEye.tsx

Fix broken styles on the TimeEye logo
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3214).
* #3216
* __->__ #3214

Fix broken styles on the TimeEye logo

---

project/zemn.me/next/pages/_app.tsx

staging.zemn.me: move meta tags into <head> element.

staging.zemn.me: move meta tags into <head> element.

---

package.json
pnpm-lock.yaml

Back out "Update dependency devtools-protocol to ^0.0.1159816"
Original commit changeset: 924ec2e49bb9
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3339).
* #3338
* __->__ #3339

Back out "Update dependency devtools-protocol to ^0.0.1159816"

---

project/zemn.me/next/BUILD.bazel
project/zemn.me/next/pages/index.tsx

Add links and, html and generic formatting to staging.zemn.me
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3216).
* #3333
* #3332
* #3301
* #3300
* #3298
* #3297
* #3284
* #3281
* #3283
* #3280
* #3279
* #3217
* __->__ #3216

Add links and, html and generic formatting to staging.zemn.me

---

bzl/fix_api/BUILD.bazel
bzl/fix_api/README.md
bzl/fix_api/fix_all.sh

Fix api docs

---

.vscode/extensions.json

Add sapling vscode plugin to the list of extension recommendations.

Add sapling vscode plugin to the list of extension recommendations.

---

project/zemn.me/bio/bio.ts
project/zemn.me/next/pages/_app.tsx
project/zemn.me/next/pages/_document.tsx
project/zemn.me/next/pages/base.css
project/zemn.me/next/pages/dotted_divider.module.css
project/zemn.me/next/pages/index.tsx
project/zemn.me/next/pages/timeline.module.css
project/zemn.me/next/pages/timeline.tsx
ts/next.js/index.tsx
ts/react/lang/index.tsx

Timeline for zemn.me
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3217).
* #3333
* #3332
* #3301
* #3300
* #3298
* #3297
* #3284
* #3281
* #3283
* #3280
* #3279
* __->__ #3217

Timeline for zemn.me

---

bin/host/ffmpeg/BUILD.bazel
bin/host/ffmpeg/ffmpeg_smoke.sh
bzl/deps.bzl

Add ffmpeg to the repo via static builds.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3280).
* #3333
* #3332
* #3301
* #3300
* #3298
* #3297
* #3284
* #3281
* #3283
* __->__ #3280

Add ffmpeg to the repo via static builds.

---

ts/pulumi/BUILD.bazel

Yaml lint tests for pulumi.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3470).
* #3376
* #3334
* #3471
* __->__ #3470

Yaml lint tests for pulumi.

---

.github/BUILD.bazel
.github/workflows/BUILD.bazel
ts/pulumi/BUILD.bazel
yml/test.bzl

Have yaml lint automatically pick up .yml and .yaml files.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3471).
* #3376
* #3334
* __->__ #3471

Have yaml lint automatically pick up .yml and .yaml files.

---

bzl/deps.bzl

Upgrade rules_nodejs to 6.0.0

---

.github/workflows/ci.yml

Perform submit and postsubmit on push. Remove rollback, which is sadly super hard to implement on push.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3522).
* #3523
* __->__ #3522

Perform submit and postsubmit on push. Remove rollback, which is sadly super hard to implement on push.

---

.github/workflows/ci.yml

Use https://github.com/easimon/maximize-build-space in github actions runners to increase disk space.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3529).
* __->__ #3529
* #3528

Use https://github.com/easimon/maximize-build-space in github actions runners to increase disk space.

---

ts/pulumi/index.ts
ts/pulumi/lib/website.ts
ts/pulumi/pleaseintroducemetoyour.dog/index.ts
ts/pulumi/shadwell.im/index.ts
ts/pulumi/zemn.me/index.ts

Implement noIndex for staging builds.

Implement noIndex for staging builds.

---

.github/workflows/ci.yml

Free up some disk space in the actions runners.

Free up some disk space in the actions runners.

---

BUILD.bazel
pnpm_lock_sync_test.sh

Test if lockfile and package.json are out of date relative to each other.

Test if lockfile and package.json are out of date relative to each other.

---

WORKSPACE

Upgrade Go to 1.20.7.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3567).
* #3570
* #3536
* #3568
* __->__ #3567

Upgrade Go to 1.20.7.

---

ci/presubmit.ts

Amend pnpm lockfile presubmit to work.

Amend pnpm lockfile presubmit to work.

---

.github/workflows/ci.yml
ci/presubmit.ts
pnpm-lock.yaml

https://github.com/pnpm/pnpm/issues/6962

https://github.com/pnpm/pnpm/issues/6962

---

ts/pulumi/BUILD.bazel
ts/pulumi/zemn.me/availability/BUILD.bazel
ts/pulumi/zemn.me/availability/pages/_app.tsx
ts/pulumi/zemn.me/availability/pages/base.css
ts/pulumi/zemn.me/availability/pages/index.tsx
ts/pulumi/zemn.me/index.ts

Implement availability.zemn.me using the normal website component.

Implement availability.zemn.me using the normal website component.

---

.editorconfig

Update .editorconfig to match Yaml standard.

Update .editorconfig to match Yaml standard.

---

.vscode/extensions.json

Add editorconfig to suggested extensions

Add editorconfig to suggested extensions

---

project/zemn.me/bio/bio.ts

Add black badge info.

---

project/zemn.me/next/pages/base.css
project/zemn.me/next/pages/index.module.css
project/zemn.me/next/pages/index.tsx

Progress on zemn.me.
1. Fix the width of the 2col layout
2. Move the logo and name into a "letterhead" thing which I've placed on the LHS.

Progress on zemn.me.

---

project/zemn.me/next/pages/index.tsx

zemn.me: fix double word

---

project/zemn.me/next/pages/_app.tsx

zemn.me: on iOS, allow content to go into "The Notch" area (also known as the "unsafe area")

zemn.me: on iOS, allow content to go into "The Notch" area (also known as the "unsafe area")

---

ts/pulumi/lib/website.ts

Remove comment that doesn't mean anything.

Remove comment that doesn't mean anything.

---

ts/pulumi/deploy_to_staging.ts

Presubmit: when --overwrite is provided, ony do a full destroy if up() fails.

Presubmit: when --overwrite is provided, ony do a full destroy if up() fails.

---

project/zemn.me/next/components/timeline/timeline.tsx

zemn.me: Add correct language tagging to timeline.

zemn.me: Add correct language tagging to timeline.

---

bzl/transcode_web/rules.bzl

Try to optimize video recording a bit better :)

Try to optimize video recording a bit better :)

---

project/zemn.me/bio/bio.ts

Update information on Google employment.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3679).
* #3680
* __->__ #3679

Update information on Google employment.

---

project/zemn.me/bio/bio.ts

zemn.me: add CVE numbers to VSCode RCE.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3680).
* __->__ #3680
* #3679

zemn.me: add CVE numbers to VSCode RCE.

---

project/zemn.me/next/pages/404.module.css
project/zemn.me/next/pages/404.tsx

zemn.me: 404 page.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3682).
* #3683
* __->__ #3682

zemn.me: 404 page.

---

.npmrc

I don't know how to fix the peer dependency issues, so I am just removing strict peer deps.

I don't know how to fix the peer dependency issues, so I am just removing strict peer deps.

---

project/zemn.me/elements/TimeEye/TimeEye.tsx
project/zemn.me/elements/ZemnmezLogo/BUILD.bazel
project/zemn.me/elements/ZemnmezLogo/ZemnmezLogo.tsx
project/zemn.me/next/BUILD.bazel
project/zemn.me/next/components/timeline/timeline.module.css
project/zemn.me/next/components/timeline/timeline.tsx
project/zemn.me/next/pages/index.module.css
project/zemn.me/next/pages/index.tsx

zemn.me: put some information at the bottom of the page.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3694).
* #3695
* __->__ #3694
* #3693
* #3692
* #3674

zemn.me: put some information at the bottom of the page.

---

project/zemn.me/next/components/timeline/timeline.tsx

Add victorian style full stops to the timeline.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3695).
* #3698
* __->__ #3695

Add victorian style full stops to the timeline.

---

project/zemn.me/bio/bio.ts
project/zemn.me/next/pages/index.module.css
project/zemn.me/next/pages/index.tsx

zemn.me: Fix the link block

---

project/zemn.me/next/BUILD.bazel
project/zemn.me/next/pages/_app.tsx
project/zemn.me/next/public/BUILD.bazel
project/zemn.me/next/public/icon.svg

zemn.me: Add web icon

---

project/zemn.me/bio/bio.ts

zemn.me: Add some more stuff to the timeline

zemn.me: Add some more stuff to the timeline

---

.vscode/extensions.json
project/zemn.me/bio/bio.ts
project/zemn.me/next/components/DividerHeading/index.module.css
project/zemn.me/next/components/DividerHeading/index.tsx
project/zemn.me/next/components/timeline/timeline.module.css
project/zemn.me/next/components/timeline/timeline.tsx
project/zemn.me/next/pages/index.module.css
project/zemn.me/next/pages/index.tsx
ts/pulumi/lib/website.ts

Add eslint to list of suggested extensions.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3704).
* __->__ #3704
* #3703
* #3702
* #3701

Add eslint to list of suggested extensions.

---

ts/pulumi/zemn.me/index.ts

zemn.me: Replace zemn.me with the new version.

zemn.me: Replace zemn.me with the new version.

---

ts/pulumi/zemn.me/index.ts

Attempt zemn.me hotfix

---

ts/pulumi/zemn.me/index.ts

Trigger submit again for hotfix.

Trigger submit again for hotfix.

---

project/zemn.me/next/pages/_document.tsx

Add a meta description.

---

bzl/deps.bzl
project/zemn.me/bio/bio.ts

zemn.me: fix typo (thanks https://twitter.com/kilgenmus!)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/Zemnmez/monorepo/pull/3719).
* __->__ #3719
* #3720

zemn.me: fix typo (thanks https://twitter.com/kilgenmus!)

---

project/zemn.me/bio/bio.ts

zemn.me: Add some old vulns missing from the timeline.

zemn.me: Add some old vulns missing from the timeline.

---

ci/BUILD.bazel
ci/presubmit.ts
ci/submit.ts
ts/github/actions/BUILD.bazel
ts/github/actions/index.ts
ts/pulumi/BUILD.bazel
ts/pulumi/deploy_to_staging.ts

Make better use of github actions annotations.

Make better use of github actions annotations.

---

ci/submit.ts
ts/pulumi/deploy_to_staging.ts

Pre/postsubmit: Actually print the summary message.

Pre/postsubmit: Actually print the summary message.

---

ts/next.js/index.tsx

Add Google Analytics because why not

Add Google Analytics because why not

---

WORKSPACE

Try to fix puppeteer by having it match https://github.com/aspect-build/rules_js/blob/main/WORKSPACE#L134

Try to fix puppeteer by having it match https://github.com/aspect-build/rules_js/blob/main/WORKSPACE#L134

---

.github/workflows/ci.yml

ci workflow: remove all github actions caches. they were bad and caused a lot of problems.

ci workflow: remove all github actions caches. they were bad and caused a lot of problems.

---

ts/pulumi/lib/website.ts

website: redirect /something.html to /something.

website: redirect /something.html to /something.

---

renovate.json

Prevent renovate from pulling bad content from the dist/ directory.

Prevent renovate from pulling bad content from the dist/ directory.

---

pnpm-lock.yaml

Upgrade devtools-protocol and puppeteer
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/3811).
* #3807
* __->__ #3811

Upgrade devtools-protocol and puppeteer

---

.bazelrc
.github/workflows/bootstrap_bazel_remote_cache.sh
.github/workflows/ci.yml
.gitignore
README.md

Integrate BuildBuddy cache.

---

bzl/transcode_web/rules.bzl

Run ffmpeg in bitexact mode so every update doesn't cause a cash bust.

Run ffmpeg in bitexact mode so every update doesn't cause a cash bust.

---

.github/workflows/ci.yml

Remove requirement on Staging to have presubmit completed so that it can complete parallel to the presubmit.

Remove requirement on Staging to have presubmit completed so that it can complete parallel to the presubmit.

---

md/disclosures/2023/github.com/brix/crypto-js.md
md/disclosures/2023/github.com/entronad/crypto-es.md

Backup the 2023 crypto es/js disclosures.

Backup the 2023 crypto es/js disclosures.

---

renovate.json

Renovate: automatically migrate own config.

Renovate: automatically migrate own config.

---

project/zemn.me/next/pages/index.module.css

zemn.me: Remove margin from the first element of a prose element.

zemn.me: Remove margin from the first element of a prose element.

---

project/zemn.me/bio/bio.ts

Add information on the two crypto-es and crypto-js issues.

Add information on the two crypto-es and crypto-js issues.

---

renovate.json

Update all renovate config reference from Zemnmez/monorepo to zemn-me/monorepo.
(this prevented renovate from doing anything)

Update all renovate config reference from Zemnmez/monorepo to zemn-me/monorepo.

---

.github/workflows/ci.yml

Use a github action to install chrome with puppeteer for testing.

Use a github action to install chrome with puppeteer for testing.

---

ts/cmd/svgshot/svgshot_test.ts

Accept SVGShot tests not passing for now.

Accept SVGShot tests not passing for now.

---

.github/versioning/versioning.md
SECURITY.md
go.mod
go/archive/zip/ziputil/BUILD.bazel
go/cmd/csvpretty/README.md
go/cmd/zipdir/zipdir.go
go/cmd/zipfiles/zipfiles.go
go/flag/flagutil/BUILD.bazel
js/npm/package_json/gen_pkgjson.ts
project/zemn.me/bio/bio.ts
ts/cmd/svgshot/lib.ts

Update all references from Zemnmez/monorepo to zemn-me/monorepo.

Update all references from Zemnmez/monorepo to zemn-me/monorepo.

---

project/zemn.me/bio/bio.ts

zemn.me/bio: update crypto-es/js links to use permalink URLs

zemn.me/bio: update crypto-es/js links to use permalink URLs

---

project/zemn.me/bio/bio.ts

Add black badge URL.

---

project/zemn.me/bio/bio.ts

zemn.me: Add Apple hall of fame entry.
fixes #3888

zemn.me: Add Apple hall of fame entry.

---

.vscode/extensions.json

Add proto3 extension to vscode extensions suggestions

Add proto3 extension to vscode extensions suggestions

---

project/zemn.me/bio/bio.ts

zemn.me: fix link to CVE-2016-2049

zemn.me: fix link to CVE-2016-2049

---

project/zemn.me/bio/bio.ts
project/zemn.me/next/BUILD.bazel
project/zemn.me/next/components/BUILD.bazel
project/zemn.me/next/components/Link/Link.tsx
project/zemn.me/next/components/Link/index.tsx
project/zemn.me/next/components/timeline/timeline.tsx
project/zemn.me/next/pages/index.tsx

Introduce Link component that correctly sets _blank for external links.

Introduce Link component that correctly sets _blank for external links.

---

project/zemn.me/bio/bio.ts

zemn.me bio: clarify that workspace trust issues talk is not mine.

zemn.me bio: clarify that workspace trust issues talk is not mine.

---

ts/pulumi/zemn.me/availability/pages/index.tsx

availability: default to WEEK mode.

availability: default to WEEK mode.

---

ts/pulumi/lib/website.ts

Website.ts: redirect xxx.html to xxx.
fixes #3905

Website.ts: redirect xxx.html to xxx.

---

ts/pulumi/zemn.me/availability/pages/index.tsx

Availability: don't show calendars

Availability: don't show calendars

---

project/zemn.me/BUILD.bazel

Alias //project/zemn.me to //project/zemn.me/next:dev
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/3947).
* #3948
* __->__ #3947

Alias //project/zemn.me to //project/zemn.me/next:dev

---

project/zemn.me/next/pages/index.tsx

zemn.me: add comment to email so email clients who don't know me pick up a name.

zemn.me: add comment to email so email clients who don't know me pick up a name.

---

project/zemn.me/next/pages/index.tsx

zemn.me: add a space to the email just to be pretty.

zemn.me: add a space to the email just to be pretty.

---

bzl/deps.bzl

Fix digest for new release of ffmpeg.

Fix digest for new release of ffmpeg.

---

ts/pulumi/lib/website.ts

Add SPF record to Website.

---

ts/iter/index.ts
ts/iter/iter_test.ts
ts/pulumi/zemn.me/availability/BUILD.bazel
ts/pulumi/zemn.me/availability/pages/index.tsx

Refactor the gCal embed syntax a bit so that we can add / remove info with simpler diffs.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/3998).
* __->__ #3998
* #3997

Refactor the gCal embed syntax a bit so that we can add / remove info with simpler diffs.

---

bzl/deps.bzl

Fix some deps and hashes.

---

.vscode/gopackagesdriver.sh
.vscode/settings.json

make vscode aware of io_rules_go

make vscode aware of io_rules_go

---

project/zemn.me/next/components/Q/index.tsx
project/zemn.me/next/pages/index.tsx

Introduce <Q> element with <Q single> attribute for single quotes.

Introduce <Q> element with <Q single> attribute for single quotes.

---

.vscode/settings.json

Have vscode automatically complete absolute imports.

Have vscode automatically complete absolute imports.

---

bzl/deps.bzl
ts/math/canvas/index.ts
ts/math/cartesian.ts

chore(deps): update dependency aspect_rules_swc to v1

chore(deps): update dependency aspect_rules_swc to v1

---

.github/workflows/ci.yml

Comment out broken postsubmit step. I don't think there's value in having it if every time it runs it's broken. It should be fixed eventually...

Comment out broken postsubmit step. I don't think there's value in having it if every time it runs it's broken. It shoul

---

bzl/deps.bzl
project/cultist/gen/BUILD.bazel

Attempt to fix https://github.com/zemn-me/monorepo/pull/3884 via removing weird line that I don't understand
chore(deps): update dependency com_google_protobuf to v25

Attempt to fix https://github.com/zemn-me/monorepo/pull/3884 via removing weird line that I don't understand

---

.github/workflows/ci.yml
ci/BUILD.bazel
ci/bazel.ts
ci/bazel_test.ts
ci/presubmit.ts
ts/github/actions/index.ts
ts/iter/async.ts

Back out "Back out "Some annotations for GitHub""
Original commit changeset: 71947c590296
Merge branch 'main' into pr3765

Back out "Back out "Some annotations for GitHub""

---

project/zemn.me/bio/bio.ts
project/zemn.me/next/pages/index.tsx
ts/pulumi/zemn.me/availability/pages/index.tsx

zemn.me bio: announce new job at OpenAI

zemn.me bio: announce new job at OpenAI

---

bzl/BUILD.bazel
bzl/run_affected_tests.sh

Modify run_affected_tests to only run tests that are affected by the change in files.
Also rename the script, the name was stupid.

Modify run_affected_tests to only run tests that are affected by the change in files.

---

ts/next.js/index.tsx

See if I can make google analytics work (due to the nature of modifying csp, I'm testing this live).

See if I can make google analytics work (due to the nature of modifying csp, I'm testing this live).

---

ts/next.js/index.tsx

Back out "See if I can make google analytics work (due to the nature of modifying csp, I'm testing this live)."
Original commit changeset: d9d6d1a756d8
Error: VM669:1 Uncaught ReferenceError: ga is not defined
at <anonymous>:1:1
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4123).
* #4124
* __->__ #4123

Back out "See if I can make google analytics work (due to the nature of modifying csp, I'm testing this live)."

---

ts/next.js/index.tsx

Tidy csp directives.

---

ts/next.js/index.tsx

Use Google Analytics 4.

---

ts/pulumi/lib/website.ts

Revert 050d0541d9f91d884a1f1ec41c70e59c8476386a to remove all txt records in preparation for adoption.

Revert 050d0541d9f91d884a1f1ec41c70e59c8476386a to remove all txt records in preparation for adoption.

---

package.json
pnpm-lock.yaml
project/zemn.me/next/BUILD.bazel
project/zemn.me/next/pages/experiments/rays.tsx

https://zemn.me/experiments/rays: use a seeded RNG so that we get the same results every time

https://zemn.me/experiments/rays: use a seeded RNG so that we get the same results every time

---

project/zemn.me/next/pages/experiments/rays.tsx
ts/cmd/svgshot/svgshot_test.ts

Skip flakey svgshot test again.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4159).
* __->__ #4159
* #4157

Skip flakey svgshot test again.

---

project/zemn.me/next/components/Prose/prose.module.css
project/zemn.me/next/components/Prose/prose.tsx
project/zemn.me/next/pages/index.module.css
project/zemn.me/next/pages/index.tsx

zemn.me: move Prose into a separate component
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4155).
* #4158
* __->__ #4155

zemn.me: move Prose into a separate component

---

CODEOWNERS

Add root CODEOWNERS file.

---

CODEOWNERS
ts/pulumi/BUILD.bazel
ts/pulumi/shadwell.im/BUILD.bazel
ts/pulumi/shadwell.im/index.ts
ts/pulumi/shadwell.im/luke/BUILD.bazel
ts/pulumi/shadwell.im/luke/pages/BUILD.bazel
ts/pulumi/shadwell.im/luke/pages/_app.tsx
ts/pulumi/shadwell.im/luke/pages/index.tsx
ts/pulumi/shadwell.im/thomas/BUILD.bazel

Give luke.shadwell.im to @steadyon.

Give luke.shadwell.im to @steadyon.

---

CODEOWNERS

add @zemnmez-renovate-bot to codeowners.

add @zemnmez-renovate-bot to codeowners.

---

project/zemn.me/next/components/BUILD.bazel
ts/next.js/index.tsx
ts/pulumi/pleaseintroducemetoyour.dog/pages/BUILD.bazel
ts/pulumi/pleaseintroducemetoyour.dog/pages/_app.tsx
ts/pulumi/pleaseintroducemetoyour.dog/pages/base.css
ts/pulumi/pleaseintroducemetoyour.dog/pages/daily.tsx

port doggos of the day to https://pleaseintroducemetoyour.dog/daily
Fixes #4140

port doggos of the day to https://pleaseintroducemetoyour.dog/daily

---

.bazelrc

BuildBuddy suggestions

---

CODEOWNERS

Alter CODEOWNERS for luke's site so I can actually modify it too.

Alter CODEOWNERS for luke's site so I can actually modify it too.

---

ts/pulumi/pleaseintroducemetoyour.dog/pages/daily.tsx

forgot the title for https://pleaseintroducemetoyour.dog/daily

forgot the title for https://pleaseintroducemetoyour.dog/daily

---

ts/pulumi/pleaseintroducemetoyour.dog/pages/daily.tsx

handle errors

---

.github/workflows/ci.yml
ci/presubmit.ts

Better use actions groups in CI.

Better use actions groups in CI.

---

ci/bazel.ts

Listen for 'error' events on the bazel subprocess.

Listen for 'error' events on the bazel subprocess.

---

CODEOWNERS
ts/pulumi/shadwell.im/BUILD.bazel
ts/pulumi/shadwell.im/index.ts
ts/pulumi/shadwell.im/kate/BUILD.bazel
ts/pulumi/shadwell.im/kate/pages/_app.tsx
ts/pulumi/shadwell.im/kate/pages/index.tsx

Add kate.shadwell.im

---

project/zemn.me/next/components/Title/title.tsx
project/zemn.me/next/pages/experiments/emoji/flag.module.css
project/zemn.me/next/pages/experiments/emoji/flag.tsx

Cute little emoji thing

---

ts/pulumi/shadwell.im/BUILD.bazel
ts/pulumi/shadwell.im/index.ts
ts/pulumi/shadwell.im/lucy/BUILD.bazel
ts/pulumi/shadwell.im/lucy/pages/_app.tsx
ts/pulumi/shadwell.im/lucy/pages/index.tsx

Add lucy.shadwell.im

---

CODEOWNERS

Have stuff renovate modifies owned by @renovate_approvers, to see if it prevnts renovatebot needing to add a reviewer.

Have stuff renovate modifies owned by @renovate_approvers, to see if it prevnts renovatebot needing to add a reviewer.

---

project/zemn.me/next/pages/_app.tsx

zemn.me: fix issue where favicon would show only on root.

zemn.me: fix issue where favicon would show only on root.

---

project/zemn.me/next/pages/experiments/rays.tsx

https://zemn.me/experiments/rays: fix logo being fully blacked out on light mode

https://zemn.me/experiments/rays: fix logo being fully blacked out on light mode

---

project/zemn.me/next/pages/experiments/index.tsx

Basic navigation for /experiments

Basic navigation for /experiments

---

project/zemn.me/next/pages/experiments/emoji/flag.tsx

/experiments/emoji/flag: accept upper case letters.

/experiments/emoji/flag: accept upper case letters.

---

project/zemn.me/next/BUILD.bazel
project/zemn.me/next/pages/experiments/rays.html.tsx
project/zemn.me/next/pages/src.tsx
ts/next.js/component/Redirect/BUILD.bazel
ts/next.js/component/Redirect/index.tsx
ts/pulumi/shadwell.im/luke/pages/BUILD.bazel
ts/pulumi/shadwell.im/luke/pages/index.tsx

Refactor redirects into a new component and redirect zemn.me/src to the monorepo url

Refactor redirects into a new component and redirect zemn.me/src to the monorepo url

---

project/zemn.me/next/app/layout.tsx

project/zemn.me/next: migrate to app router (1) _document.tsx
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4288).
* #4289
* __->__ #4288

project/zemn.me/next: migrate to app router (1) _document.tsx

---

project/zemn.me/next/app/ClientLayout.tsx
project/zemn.me/next/app/base.css
project/zemn.me/next/app/layout.tsx

project/zemn.me/next: migrate to app router (2) _app.tsx
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4289).
* #4292
* __->__ #4289

project/zemn.me/next: migrate to app router (2) _app.tsx

---

ts/next.js/next.config.ts
ts/next.js/rules.bzl

ts/next.js: update next config to be compatible with static app router export.
https://nextjs.org/docs/pages/building-your-application/deploying/static-exports
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4296).
* #4297
* __->__ #4296

ts/next.js: update next config to be compatible with static app router export.

---

ts/next.js/component/Redirect/app.tsx

ts/next.js/component/Redirect: add app router compatible version.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4299).
* #4297
* __->__ #4299

ts/next.js/component/Redirect: add app router compatible version.

---

ts/next.js/rules.bzl

ts/next.js: Add sharp as a dep so next.js picks it up automatically.

ts/next.js: Add sharp as a dep so next.js picks it up automatically.

---

project/zemn.me/next/app/src/page.tsx

project/zemn.me/next: migrate to app router: migrate /src

project/zemn.me/next: migrate to app router: migrate /src

---

.gitignore

Add sl to gitignore

---

.vscode/gopackagesdriver.sh
.vscode/testing/BUILD.bazel
.vscode/testing/test_tools_run.sh

Smoke test for gopackagesdriver

Smoke test for gopackagesdriver

---

ts/pulumi/BUILD.bazel
ts/pulumi/index.ts
ts/pulumi/lib/certificate.ts
ts/pulumi/lib/website.ts
ts/pulumi/lulu.computer/BUILD.bazel
ts/pulumi/lulu.computer/app/layout.tsx
ts/pulumi/lulu.computer/app/page.tsx
ts/pulumi/lulu.computer/index.ts

lulu.computer

---

ts/pulumi/lulu.computer/index.ts

lulu.computer: appropriately parent RegisteredDomain

lulu.computer: appropriately parent RegisteredDomain

---

.vscode/go.sh
.vscode/gopackagesdriver.sh
.vscode/settings.json
sh/bin/README.md
sh/bin/go
sh/bin/gopackagesdriver
sh/run_bazel.sh

Standardise calling bazel binaries from outside of bazel and rework .vscode integrations to use it.

Standardise calling bazel binaries from outside of bazel and rework .vscode integrations to use it.

---

.vscode/settings.json
.vscode/testing/BUILD.bazel
.vscode/testing/test_tools_run.sh
bzl/go_deps.bzl
go.mod
go.sum
sh/bin/goimports
sh/tools.go

build goimports binary with bazel

build goimports binary with bazel

---

.vscode/settings.json
.vscode/testing/BUILD.bazel
.vscode/testing/test_tools_run.sh
bzl/go_deps.bzl
go.mod
go.sum
sh/bin/staticcheck
sh/tools.go

Use rules_go based staticcheck binary
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4364).
* #4365
* __->__ #4364

Use rules_go based staticcheck binary

---

.vscode/settings.json

Update .vscode/settings.json to match one updated by vscode

Update .vscode/settings.json to match one updated by vscode

---

sh/run_bazel.sh

Allow progress on bazel / bazelisk.

Allow progress on bazel / bazelisk.

---

renovate.json

Renovate: group up changes to the pulumi cli

Renovate: group up changes to the pulumi cli

---

project/zemn.me/app/github/page.tsx
project/zemn.me/app/linkedin/page.tsx
project/zemn.me/app/twitter/page.tsx
project/zemn.me/bio/bio.ts
ts/next.js/component/Redirect/app.tsx

add redirects to zemn.me:
- https://zemn.me/{twitter,github,linkedin}
Also make the types for Bio a bit more exact so we're sure not to delete this data.
Fixes https://github.com/zemn-me/monorepo/issues/4399
Fixes #4399

add redirects to zemn.me:

---

project/zemn.me/bio/bio.ts

zemn.me/bio: add Shmoocon 2024

zemn.me/bio: add Shmoocon 2024

---

bzl/deps.bzl

Upgrade rules_proto.

---

sh/bin/BUILD.bazel
sh/bin/pnpm

sh/bin: add pnpm

---

ci/bazel.ts
ci/presubmit.ts

Use bazelisk for presubmit

---

ci/presubmit.ts

ci/presubmit: run all tests even if some fail.

ci/presubmit: run all tests even if some fail.

---

ci/postsubmit.ts
tsconfig.json

tsconfig.json: enable noImplicitOverride

tsconfig.json: enable noImplicitOverride

---

project/zemn.me/bio/bio.ts

VOD for HF this year

---

project/zemn.me/app/page.tsx
project/zemn.me/bio/bio.ts

I forgot to make a title for zemn.me

I forgot to make a title for zemn.me

---

bin/host/chromedriver/BUILD.bazel
bin/host/chromedriver/chromedriver_smoke.sh
bzl/deps.bzl
renovate.json

Add chromedriver

---

js/jest/rules.bzl
package.json
pnpm-lock.yaml
project/zemn.me/testing/BUILD.bazel
project/zemn.me/testing/browser_test.ts
ts/next.js/index.tsx

Use selenium to check that zemn.me loads without errors.

Use selenium to check that zemn.me loads without errors.

---

.eslintrc.json
js/eslint/private/BUILD.bazel
package.json
pnpm-lock.yaml
project/zemn.me/app/experiments/rays/component.tsx

Enable eslint-react-hooks.

---

project/zemn.me/app/style.module.css

zemn.me: some padding before links. should have done this ages ago

zemn.me: some padding before links. should have done this ages ago

---

project/zemn.me/app/base.css

Support color-scheme.

---

bzl/deps.bzl

Remove vestigial comment.

---

.eslintrc.json
js/eslint/private/BUILD.bazel
package.json
pnpm-lock.yaml

Enable @next/eslint-plugin-next

Enable @next/eslint-plugin-next

---

project/zemn.me/app/layout.tsx
project/zemn.me/app/page.tsx
project/zemn.me/testing/browser_test.ts

Fuck around with metadata again

Fuck around with metadata again

---

bzl/deps.bzl

Remove weird incorrect bazel_tools dep.

Remove weird incorrect bazel_tools dep.

---

.bazelrc
bzl/deps.bzl

Sha256 for caching aspect_rules_ts.

Sha256 for caching aspect_rules_ts.

---

.vscode/settings.json

Enable images in the terminal (why not?)

Enable images in the terminal (why not?)

---

.vscode/settings.json

add sh/bin to PATH of vscode shell, so it has repo tools.

add sh/bin to PATH of vscode shell, so it has repo tools.

---

CODEOWNERS

Allow one person approvals because GitHub sucks.

Allow one person approvals because GitHub sucks.

---

ts/pulumi/index.ts
ts/pulumi/lib/certificate.ts
ts/pulumi/lib/tags.ts
ts/pulumi/lib/website.ts
ts/pulumi/lulu.computer/index.ts
ts/pulumi/pleaseintroducemetoyour.dog/index.ts
ts/pulumi/shadwell.im/index.ts
ts/pulumi/zemn.me/index.ts

Tags tracking pulumi shape in aws.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4539).
* #4542
* __->__ #4539

Tags tracking pulumi shape in aws.

---

ts/pulumi/index.ts
ts/pulumi/lib/certificate.ts
ts/pulumi/lib/website.ts
ts/pulumi/lulu.computer/index.ts
ts/pulumi/pleaseintroducemetoyour.dog/index.ts
ts/pulumi/shadwell.im/index.ts
ts/pulumi/zemn.me/index.ts

Cost allocation tracking.

---

project/zemn.me/app/experiments/factorio/blueprint/page.tsx

Factorio: missed this page

---

package.json
pnpm-lock.yaml
project/zemn.me/testing/BUILD.bazel
project/zemn.me/testing/browser_test.ts

Browser testing: load all next.js endpoints.

Browser testing: load all next.js endpoints.

---

ts/pulumi/index.ts

Pulumi: add a budget.

---

ts/react/PrettyJSON/pretty_json.tsx

Fix some issues with the JSON pretty printer.

Fix some issues with the JSON pretty printer.

---

project/zemn.me/app/experiments/factorio/blueprint/page.tsx
project/zemn.me/app/experiments/page.tsx
project/zemn.me/testing/browser_test.ts

Actually ensure that multi-page testing happens. Fix some issues it flagged.

Actually ensure that multi-page testing happens. Fix some issues it flagged.

---

project/zemn.me/app/experiments/factorio/page.tsx

Fix factorio page listing.

---

project/zemn.me/app/healthcheck/bad/README.md
project/zemn.me/app/healthcheck/bad/client.tsx
project/zemn.me/app/healthcheck/bad/page.tsx
project/zemn.me/testing/browser_test.ts

zemn.me: Introduce a page that should fail.

zemn.me: Introduce a page that should fail.

---

BUILD.bazel
bzl/deps.bzl
ts/factorio/data/1.1/BUILD.bazel
ts/factorio/data/1.1/types.ts

Add factorio types from FactorioLab to the monorepo.

Add factorio types from FactorioLab to the monorepo.

---

project/zemn.me/app/src/[[...slug]]/page.tsx

zemn.me: prerender zemn.me/src/*

zemn.me: prerender zemn.me/src/*

---

project/zemn.me/testing/browser_test.ts

zemn.me: fix browser tests by not collecting logs not from localhost.

zemn.me: fix browser tests by not collecting logs not from localhost.

---

project/zemn.me/app/experiments/factorio/blueprint/blueprint.tsx
project/zemn.me/app/experiments/factorio/blueprint/page.tsx
project/zemn.me/app/experiments/factorio/blueprint/wall/client.tsx
project/zemn.me/app/experiments/factorio/blueprint/wall/page.tsx
ts/factorio/BUILD.bazel
ts/factorio/blueprint.ts
ts/math/cartesian.ts
ts/math/math_test.ts

Factorio wall experiment.

---

project/zemn.me/app/layout.tsx

zemn.me: add a default title and title template

zemn.me: add a default title and title template

---

.eslintrc.json
ci/bazel.ts
ci/postsubmit.ts
ci/presubmit.ts
ci/submit.ts
js/jest/jest_reporter.ts
js/npm/package_json/gen_pkgjson.ts
js/testing/simple_binary_import/main.ts
project/cultist/gen/collate_game_core.ts
project/cultist/save_test.ts
project/zemn.me/app/experiments/emoji/flag/component.tsx
project/zemn.me/app/experiments/factorio/blueprint/blueprint.tsx
project/zemn.me/app/healthcheck/bad/client.tsx
project/zemn.me/bio/sort_tool/sort_tool.ts
ts/cmd/svgshot/lib.ts
ts/cmd/svgshot/run.ts
ts/do-sync/doSync.ts
ts/factorio/blueprint.ts
ts/force_buffer_whole_video/force_buffer_whole_video.ts
ts/math/matrix.ts
ts/next.js/testing/example/launch_server_test.ts
ts/next.js/testing/example/pages/index.tsx
ts/pulumi/deploy_to_staging.ts
ts/pulumi/pleaseintroducemetoyour.dog/pages/daily.tsx
ts/pulumi/preview.ts
ts/react/CopyToClipboard/CopyToClipboard.tsx
ts/svg/scale.tsx

eslint: block usage of console.*

eslint: block usage of console.*

---

project/zemn.me/app/experiments/factorio/blueprint/blueprint.tsx

zemn.me: null out the messy 'DisplayGamespace' component from the factorio experiments

zemn.me: null out the messy 'DisplayGamespace' component from the factorio experiments

---

package.json
pnpm-lock.yaml
project/zemn.me/app/providers.tsx
ts/react/CopyToClipboard/BUILD.bazel
ts/react/CopyToClipboard/CopyToClipboard.tsx

replace react-query with @tanstack/react-query
original changeset: 8a619de44c54750e7b353e8306ce6dbca21786a7

replace react-query with @tanstack/react-query

---

ts/iter/index.ts

ts/iter: introduce zip2

---

.vscode/settings.json
BUILD.bazel
bzl/BUILD.bazel
bzl/deps.bzl
bzl/rules.bzl

Add a demonstration bazel lint rule, and configure bazel to be formatted automatically.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4627).
* #4628
* __->__ #4627

Add a demonstration bazel lint rule, and configure bazel to be formatted automatically.

---

.vscode/extensions.json
.vscode/settings.json
.vscode/tasks.json

Autoformat json.

---

bin/host/buildozer/BUILD.bazel
bin/host/buildozer/smoke.sh
sh/bin/BUILD.bazel
sh/bin/buildozer
ts/pulumi/zemn.me/availability/BUILD.bazel

Add buildozer binary to the monorepo and editor PATH.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4629).
* #4631
* #4630
* __->__ #4629

Add buildozer binary to the monorepo and editor PATH.

---

sh/run_bazel.sh

run_bazel to run in real workspace directory
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4630).
* #4631
* __->__ #4630

run_bazel to run in real workspace directory

---

.eslintrc.json
project/zemn.me/app/experiments/factorio/blueprint/page.tsx
project/zemn.me/components/BUILD.bazel
project/zemn.me/components/Link/Link.tsx
ts/pulumi/pleaseintroducemetoyour.dog/pages/index.tsx
ts/pulumi/zemn.me/availability/BUILD.bazel
ts/pulumi/zemn.me/availability/pages/index.tsx
ts/react/element/link/link_test.tsx

Forbid <a> and <NextLink> tags that might result in JavaScript URI injection.

Forbid <a> and <NextLink> tags that might result in JavaScript URI injection.

---

project/zemn.me/bio/bio.ts

Fix broken shmoo 2024 HF finals link

Fix broken shmoo 2024 HF finals link

---

project/zemn.me/BUILD.bazel
project/zemn.me/app/page.tsx
project/zemn.me/assets/kenwood_snow/BUILD.bazel
project/zemn.me/assets/kenwood_snow/kenwood_snow.tsx
project/zemn.me/public/BUILD.bazel
video/2017/08/27/BUILD.bazel
video/2018/03/01/BUILD.bazel

Add kenwood snow version for winter
Fixes https://github.com/zemn-me/monorepo/issues/4473
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4472).
* #4650
* __->__ #4472

Add kenwood snow version for winter

---

ts/pulumi/lib/bucketName.ts
ts/pulumi/lib/website.ts

Abstract out pulumi's bucket name generator.

Abstract out pulumi's bucket name generator.

---

ts/pulumi/lib/s3Uri.ts

S3 uri helper

---

package.json
pnpm-lock.yaml
ts/pulumi/BUILD.bazel
ts/pulumi/lib/contact_flow.ts
ts/pulumi/zemn.me/index.ts
ts/pulumi/zemn.me/voice/voice.ts

Add a test number which when called says hello, world!

Add a test number which when called says hello, world!

---

project/zemn.me/bio/bio.ts

Fix typo in https://zemn.me/#41b9fa28-bffa-4506-8e86-1bc3b2880c2f

Fix typo in https://zemn.me/#41b9fa28-bffa-4506-8e86-1bc3b2880c2f

---

ts/factorio/blueprint.ts
ts/math/tuple.ts

Introduce ts/math/tuple#extent, and use it in blueprintExtent.

Introduce ts/math/tuple#extent, and use it in blueprintExtent.

---

ts/react/CopyToClipboard/CopyToClipboard.tsx

Prevent copy to clipboard navigating on mobile.

Prevent copy to clipboard navigating on mobile.

---

js/eslint/private/eslint.bzl

Mark all eslint tests of size "medium"

Mark all eslint tests of size "medium"

---

ts/factorio/uint.ts

Fix big mistake in making uints need to be > 0

Fix big mistake in making uints need to be > 0

---

ts/factorio/testing/BUILD.bazel
ts/factorio/testing/blueprint_test.ts
ts/factorio/testing/render_to_braille.ts

Test the blueprint stuff (looks like the wall gen is actually not working rn lmao)

Test the blueprint stuff (looks like the wall gen is actually not working rn lmao)

---

js/eslint/private/eslint.bzl

Actually make eslint test size small

Actually make eslint test size small

---

renovate.json

Allow renovate to modify go.mod and go_version.bzl

Allow renovate to modify go.mod and go_version.bzl

---

go.mod
go_version.bzl

Upgrade Go to 1.22.1

---

ts/factorio/arithmetic_combinator_parameters.ts
ts/factorio/blueprint.ts
ts/factorio/blueprint_book.ts
ts/factorio/blueprint_wrapper.ts
ts/factorio/circuit_condition.ts
ts/factorio/color.ts
ts/factorio/connection.ts
ts/factorio/connection_data.ts
ts/factorio/connection_point.ts
ts/factorio/constant_combinator_parameters.ts
ts/factorio/control_behavior.ts
ts/factorio/decider_combinator_parameters.ts
ts/factorio/deconstruction_planner.ts
ts/factorio/entity.ts
ts/factorio/icon.ts
ts/factorio/infinity_filter.ts
ts/factorio/infinty_settings.ts
ts/factorio/inventory.ts
ts/factorio/item_filter_object.ts
ts/factorio/logistic_filter.ts
ts/factorio/position.ts
ts/factorio/programmable_speaker_circuit_parameters.ts
ts/factorio/schedule.ts
ts/factorio/schedule_record.ts
ts/factorio/signal_id.ts
ts/factorio/speaker_alert_parameter.ts
ts/factorio/speaker_parameter.ts
ts/factorio/tile.ts
ts/factorio/wait_condition.ts

Use strict zod objects.

---

MODULE.bazel
MODULE.bazel.lock
ts/next.js/rules.bzl

Add rules_oci and aspect_bazel_lib
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4907).
* #4892
* #4906
* __->__ #4907

Add rules_oci and aspect_bazel_lib

---

MODULE.bazel.lock
js/npm/rules.bzl

Fix js/npm/rules.bzl ordering
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4940).
* #4927
* __->__ #4940

Fix js/npm/rules.bzl ordering

---

ts/pulumi/pleaseintroducemetoyour.dog/app/daily/client.tsx

pleaseintroducemetoyour.dog: move dog footer to the right place.

pleaseintroducemetoyour.dog: move dog footer to the right place.

---

ts/next.js/next.config.ts

Next.js: include source maps in production builds. It's open source after all!

Next.js: include source maps in production builds. It's open source after all!

---

ts/next.js/BUILD.bazel
ts/next.js/config_validate_test.ts

Next.js config type check

---

ts/rules.bzl

Fix for change I accidentally force-pushed.

Fix for change I accidentally force-pushed.

---

ts/math/BUILD.bazel
ts/math/camera.ts
ts/math/canvas/element.tsx
ts/math/cartesian.ts
ts/math/conv.ts
ts/math/math_test.ts
ts/math/matrix.ts
ts/math/shape/index.ts
ts/math/vec.ts
ts/svg/index.tsx
ts/svg/scale.tsx
ts/tuple.ts

Use tuples for vectors.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/4958).
* #4967
* __->__ #4958

Use tuples for vectors.

---

MODULE.bazel
MODULE.bazel.lock
bzl/deps.bzl

Move bazel skylib to module.bazel

Move bazel skylib to module.bazel

---

bzl/deps.bzl

Remove rules_typescript_proto

---

MODULE.bazel
MODULE.bazel.lock
bzl/deps.bzl

Move rules_pkg to MODULE.bazel

Move rules_pkg to MODULE.bazel

---

MODULE.bazel
MODULE.bazel.lock
WORKSPACE
bzl/deps.bzl
py/yamllint/BUILD.bazel

Move rules_python to module.bazel

Move rules_python to module.bazel

---

MODULE.bazel
MODULE.bazel.lock
bzl/deps.bzl

Move aspect_rules_swc to bzlmod

Move aspect_rules_swc to bzlmod

---

MODULE.bazel
MODULE.bazel.lock
WORKSPACE

Move rules_proto to module.bazel

Move rules_proto to module.bazel

---

MODULE.bazel
WORKSPACE
bzl/deps.bzl

Move aspect_rules_js to bzlmod

Move aspect_rules_js to bzlmod

---

MODULE.bazel

amend distroless_base to use reproducible build.

amend distroless_base to use reproducible build.

---

.bazelrc
.github/workflows/bootstrap_bazel_remote_cache.sh
.github/workflows/ci.yml
.github/workflows/prepare_ci.sh

Set lockfile checking mode to error for CI.

Set lockfile checking mode to error for CI.

---

ci/bazel.ts
ci/bazel_test.ts

Make it an error to add a file to MODULE.bazel that is not cached.

Make it an error to add a file to MODULE.bazel that is not cached.

---

WORKSPACE

Remove vestigial aspect_rules_swc code.

Remove vestigial aspect_rules_swc code.

---

WORKSPACE

Remove vestigial rules_js stuff

Remove vestigial rules_js stuff

---

MODULE.bazel
WORKSPACE

Move aspect_rules_ts to MODULE.bazel

Move aspect_rules_ts to MODULE.bazel

---

ini/sl/config.ini
ini/sl/sync.ini

Add sapling config.

---

package.json
pnpm-lock.yaml
ts/next.js/next.config.ts
ts/next.js/rules.bzl

Allow next.js to consume input source maps.

Allow next.js to consume input source maps.

---

ts/pulumi/lib/security.txt

Remove invalid Acknowledgements directive from security.txt

Remove invalid Acknowledgements directive from security.txt

---

renovate.json

Set automerge type to branch.

---

renovate.json

Ask renovate to do lockfile maintainance.

Ask renovate to do lockfile maintainance.

---

renovate.json

Unbreak renovate.

---

ts/react/PrettyJSON/pretty_json.tsx

Limit JSON depth rendering

---

project/zemn.me/app/experiments/factorio/blueprint/parse/client.tsx
ts/factorio/react/blueprint.tsx
ts/next.js/index.tsx
ts/react/CopyToClipboard/CopyToClipboard.tsx

Greatly speed up CopyToClipboard by having it accept a function to generate its value.

Greatly speed up CopyToClipboard by having it accept a function to generate its value.

---

package.json
pnpm-lock.yaml
ts/pulumi/pleaseintroducemetoyour.dog/app/daily/client.tsx
ts/react/CopyToClipboard/CopyToClipboard.tsx

fix(deps): update dependency @tanstack/react-query to v5

fix(deps): update dependency @tanstack/react-query to v5

---

.github/workflows/ci.yml

Try again to fix up renovate branch flow.

Try again to fix up renovate branch flow.

---

bzl/transcode_web/rules.bzl
go/flag/flagutil/fileflag.go
go/img/cmd/transcode/BUILD.bazel
go/img/cmd/transcode/image_types.go
go/img/cmd/transcode/transcode.go
image/BUILD.bazel
image/transcode.bzl
project/zemn.me/assets/kenwood/BUILD.bazel
project/zemn.me/assets/kenwood/kenwood.tsx
ts/react/source/image/rules.bzl

Introduce image transcoding code, and transcode website banner.

Introduce image transcoding code, and transcode website banner.

---

.vscode/settings.json

Try cleaning up some eslint config related stuff.

Try cleaning up some eslint config related stuff.

---

project/zemn.me/assets/kenwood_snow/BUILD.bazel
project/zemn.me/assets/kenwood_snow/kenwood_snow.tsx

Kenwood_snow to also use jpg

---

project/zemn.me/README.md

Readme for project/zemn.me

---

project/cultist/README.md

README for project/cultist

---

renovate.json

Back out "Set automerge type to branch."
It is not possible via a merge queue :(
https://github.com/renovatebot/renovate/discussions/28775#discussioncomment-9294542
Original commit changeset: af013668e9cc

Back out "Set automerge type to branch."

---

project/cultist/react/table.tsx

Cultist: render decks, and don't display a missing verison number.

Cultist: render decks, and don't display a missing verison number.

---

project/zemn.me/bio/bio.ts

Reminisce about some really old work experience I did.

Reminisce about some really old work experience I did.

---

.gitignore

Gitignore MODULE.bazel.lock

---

project/zemn.me/app/base.css
project/zemn.me/app/layout.tsx

Use next.js font loaders.

---

sh/bin/BUILD.bazel
sh/bin/buildifier

Add buildifier to shell.

---

bzl/deps.bzl

Remove aspect_rules_ts from deps.bzl (it's in the bazel module).

Remove aspect_rules_ts from deps.bzl (it's in the bazel module).

---

.github/workflows/ci.yml
MODULE.bazel.lock

Cancel a previous presumbit when a new change comes in.

Cancel a previous presumbit when a new change comes in.

---

mdx/article/2014/csp.mdx

When Security Generates Insecurity: link to archived copy

When Security Generates Insecurity: link to archived copy

---

mdx/article/2014/csp.mdx
mdx/article/2016/vault_tec.mdx
mdx/article/2020/psychiatry/index.mdx
package.json
pnpm-lock.yaml
ts/mdx/cmd/mdx-transform/BUILD.bazel
ts/mdx/cmd/mdx-transform/main.ts

mdx: integrate frontmatter as an export.

mdx: integrate frontmatter as an export.

---

ts/react/lang/useLocale.tsx

useLocale: always have at least one language.

useLocale: always have at least one language.

---

MODULE.bazel.lock
project/zemn.me/testing/browser_test.ts
ts/selenium/webdriver.ts

zemn.me: restructure browser test with more context

zemn.me: restructure browser test with more context

---

project/zemn.me/app/BUILD.bazel
project/zemn.me/app/article/2014/csp/BUILD.bazel
project/zemn.me/app/article/2014/csp/page.tsx
project/zemn.me/app/article/2014/csp/style.module.css
project/zemn.me/app/page.tsx
project/zemn.me/app/style.module.css
project/zemn.me/assets/kenwood/kenwood.tsx
project/zemn.me/assets/kenwood_snow/kenwood_snow.tsx
project/zemn.me/components/HeroVideo/BUILD.bazel
project/zemn.me/components/HeroVideo/hero_video.tsx
project/zemn.me/components/HeroVideo/style.module.css
ts/react/lang/BUILD.bazel
ts/react/lang/date.tsx

Attempt at an article renderer.
zemn.me: abstract hero video to own component.

Attempt at an article renderer.

---

MODULE.bazel
MODULE.bazel.lock
package.json
pnpm-lock.yaml

typescript version to be pulled from package.json

typescript version to be pulled from package.json

---

MODULE.bazel.lock
project/zemn.me/assets/kenwood/BUILD.bazel
project/zemn.me/assets/kenwood/kenwood.tsx
project/zemn.me/assets/kenwood_snow/BUILD.bazel
project/zemn.me/assets/kenwood_snow/kenwood_snow.tsx
project/zemn.me/public/BUILD.bazel
project/zemn.me/public/kenwood.ts
project/zemn.me/public/kenwood_snow.ts

Second attempt at fixing https://github.com/zemn-me/monorepo/pull/5257 by moving files around.

Second attempt at fixing https://github.com/zemn-me/monorepo/pull/5257 by moving files around.

---

tsconfig.json

Change ts module resolution to "preserve".

Change ts module resolution to "preserve".

---

ts/fs/index.ts

ts/fs: add parentPath for forward compatibility with new DirEnt.

ts/fs: add parentPath for forward compatibility with new DirEnt.

---

ts/math/vec.ts

math vec New: clearer first arg annotation

math vec New: clearer first arg annotation

---

ts/time/BUILD.bazel
ts/time/date.ts
ts/time/date_test.ts

SimpleDate via zod instead.

---

MODULE.bazel.lock
ts/time/date.ts
ts/time/date_test.ts

ts/time: fix date parsing and add a test so I don't break it again.

ts/time: fix date parsing and add a test so I don't break it again.

---

ini/sl/config.ini
ini/sl/non_overlapping_prs.ini

Use non-overlapping PRs for sapling.

Use non-overlapping PRs for sapling.

---

project/zemn.me/components/Article/article.tsx

Use zod parser with article date.

Use zod parser with article date.

---

.vscode/extensions.json

Recommend the unicode picker extension.

Recommend the unicode picker extension.

---

.vscode/settings.json

Add global ruler.
---
* #5699
* __->__ #5704

Add global ruler.

---

eslint.config.js
project/zemn.me/components/HeroVideo/BUILD.bazel
project/zemn.me/components/HeroVideo/hero_video.tsx
ts/pulumi/pleaseintroducemetoyour.dog/app/BUILD.bazel
ts/pulumi/pleaseintroducemetoyour.dog/app/daily/client.tsx
ts/react/Video/BUILD.bazel
ts/react/Video/video.tsx
ts/react/useMediaQuery/BUILD.bazel
ts/react/useMediaQuery/useMediaQuery.ts

zemn.me: support reduced motion.

zemn.me: support reduced motion.

---

project/zemn.me/app/src/[[...slug]]/page.tsx

Fix zemn.me/src

---

.gitattributes

Mark lockfiles as generated files.

Mark lockfiles as generated files.

---

.vscode/prep/BUILD.bazel
.vscode/prep/scm_conf.py
.vscode/tasks.json

automatically configure sapling on repo load.

automatically configure sapling on repo load.

---

.gitignore
package.json
pnpm-lock.yaml
project/zemn.me/app/experiments/BUILD.bazel
project/zemn.me/app/experiments/article/BUILD.bazel
project/zemn.me/app/experiments/article/page.tsx
project/zemn.me/app/experiments/article/test.mdx
project/zemn.me/components/Article/style.module.css
ts/mdx/cmd/mdx-transform/BUILD.bazel
ts/mdx/cmd/mdx-transform/main.ts

zemn.me: add article test renderer and tweak article rendering.

zemn.me: add article test renderer and tweak article rendering.

---

.gitattributes

Mark go.sum as a generated file.

Mark go.sum as a generated file.

---

renovate.json

Renovate to update MODULE.bazel.lock

Renovate to update MODULE.bazel.lock

---

MODULE.bazel
MODULE.bazel.lock
bzl/deps.bzl

Move bazel_features to MODULE.bazel
---
* #5843
* __->__ #5840

Move bazel_features to MODULE.bazel

---

MODULE.bazel
MODULE.bazel.lock
WORKSPACE
bzl/deps.bzl

Bazel formatting fixes
---
* __->__ #5843
* #5840

Bazel formatting fixes

---

ts/next.js/component/Redirect/BUILD.bazel
ts/next.js/component/Redirect/app.tsx
ts/next.js/component/Redirect/blurb.tsx
ts/next.js/component/Redirect/index.tsx

Redirects to show target.

---

ts/pulumi/lib/certificate.ts
ts/pulumi/lib/website.ts
ts/pulumi/shadwell.im/BUILD.bazel
ts/pulumi/shadwell.im/anna/BUILD.bazel
ts/pulumi/shadwell.im/anna/pages/_app.tsx
ts/pulumi/shadwell.im/anna/pages/index.tsx
ts/pulumi/shadwell.im/index.ts

Add anna.shadwell.im

---

sh/bin/BUILD.bazel

Add gazelle to vscode shell.

---

ci/presubmit.ts

presubmit: annotate some commands, and check gazelle.

presubmit: annotate some commands, and check gazelle.

---

renovate.json

renovate: perform postupgrade actions for pip.

renovate: perform postupgrade actions for pip.

---

py/testing/renovate_json_is_valid/BUILD.bazel
py/testing/renovate_json_is_valid/renovate_json_is_valid_test.py
renovate.json

Fix JSON syntax error in renovate.json, and add a test for it.

Fix JSON syntax error in renovate.json, and add a test for it.

---

renovate.json

Fix mod deps command for bazelisk.

Fix mod deps command for bazelisk.

---

ci/presubmit.ts

Validate the PNPM lockfile only after other tests have passed.

Validate the PNPM lockfile only after other tests have passed.

---

renovate.json

Try to fix renovate error:
https://github.com/zemn-me/monorepo/pull/5988#issuecomment-2223276184

Try to fix renovate error:

---

BUILD.bazel
renovate.json

Implement fix api for requirements.txt.
Also run fix all twice.

Implement fix api for requirements.txt.

---

MODULE.bazel
go.mod
go.sum
go/encoding/jsonc/BUILD.bazel
go/encoding/jsonc/parse.go
go/encoding/jsonc/parse_test.go
go/encoding/jsonc/testdata/BUILD.bazel
go/encoding/jsonc/testdata/example.go

Add jsonc format

---

go/encoding/jsonc/parse_test.go
go/encoding/jsonc/testdata/BUILD.bazel
go/encoding/jsonc/testdata/example2.go

More tests for jsonc

---

ini/sl/merge_tools/bazel_lockfile/config.ini

Fix bazel lockfile merge tool for sapling

Fix bazel lockfile merge tool for sapling

---

Cargo.toml

Add note to Cargo.toml on how to update it.
---
* #6024
* #6048
* __->__ #6045

Add note to Cargo.toml on how to update it.

---

.vscode/settings.json

Format rust files on save.
---
* #6024
* #6051
* #6050
* __->__ #6048

Format rust files on save.

---

rs/rules.bzl

Add testing to rust rules.

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
cargo-bazel-lock.json
rs/ts/cmd/extract_imports/BUILD.bazel
rs/ts/cmd/extract_imports/main.rs
rs/ts/cmd/extract_imports/testing/BUILD.bazel
rs/ts/cmd/extract_imports/testing/a.ts
rs/ts/cmd/extract_imports/testing/expected.txt
rs/ts/extract_imports/BUILD.bazel
rs/ts/extract_imports/lib.rs

Introduce extract_imports, a rust binary which can extract typescript import lists.
---
* #6024
* __->__ #6050

Introduce extract_imports, a rust binary which can extract typescript import lists.

---

.gitignore
sh/bin/dlv
sh/bin/go
sh/bin/gofmt
sh/bin/goimports
sh/bin/gojq
sh/bin/gopackagesdriver
sh/bin/ruff
sh/bin/run_lazily.sh
sh/bin/staticcheck

Add script to run bazel scripts without throttling the lock.

Add script to run bazel scripts without throttling the lock.

---

sh/bin/gazelle
sh/bin/run_lazily.sh

Fix some issues with run_lazily
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/6067).
* #6024
* __->__ #6067

Fix some issues with run_lazily

---

sh/bin/run_lazily.sh

Fix timestamp detection for run_lazily.sh

Fix timestamp detection for run_lazily.sh

---

project/zemn.me/app/experiments/frame/client.tsx
project/zemn.me/app/experiments/frame/page.tsx

zemn.me: framing calculator

---

project/zemn.me/app/experiments/frame/client.tsx

zemn.me: framing experiment to support inches mm and cm units.

zemn.me: framing experiment to support inches mm and cm units.

---

rs/ts/cmd/extract_imports/testing/a.ts
rs/ts/cmd/extract_imports/testing/expected.txt
rs/ts/extract_imports/lib.rs

extract_imports: extract named wildcard import
---
* #6024
* #6109
* __->__ #6074

extract_imports: extract named wildcard import

---

project/zemn.me/app/experiments/factorio/BUILD.bazel
project/zemn.me/app/experiments/factorio/blueprint/parse/client.tsx
ts/factorio/react/BUILD.bazel
ts/factorio/react/blueprint.tsx
ts/zod/BUILD.bazel
ts/zod/util.ts

Factorio blueprints to parse more safely.

Factorio blueprints to parse more safely.

---

package.json
pnpm-lock.yaml
project/zemn.me/app/experiments/BUILD.bazel
project/zemn.me/app/experiments/frame/client.tsx

zemn.me/experiments/frame:
- Add visualisation for picture in frame
- Add params to URL so you don't lose them if the page reloads

zemn.me/experiments/frame:

---

renovate.json

Remove PR limits for renovate.

Remove PR limits for renovate.

---

renovate.json

renovate: Move module fixes up for renovate so fixes don't get in a broken state.

renovate: Move module fixes up for renovate so fixes don't get in a broken state.

---

.editorconfig
.vscode/settings.json
Cargo.Bazel.lock
Cargo.lock
Cargo.toml
cargo-bazel-lock.json
rs/cmd/discord_blackball_bot/BUILD.bazel
rs/cmd/discord_blackball_bot/main.rs
src/main.rs

Commit basic discord bot

---

renovate.json

Add a go mod tidy step for renovate.

Add a go mod tidy step for renovate.

---

renovate.json

Removate: include changelog in commit message.

Removate: include changelog in commit message.

---

BUILD.bazel
bzl/fix_api/BUILD.bazel
bzl/fix_api/fix_all.sh
requirements.in

Allow fix api to be run via `bazel run fix [target]`.
Also allow fix api to do 2 fixes at a time.

Allow fix api to be run via `bazel run fix [target]`.

---

BUILD.bazel
go/gazelle/venv/package.go

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/6242).
* #6243
* __->__ #6242

Include python binaries in venv.

---

project/zemn.me/app/experiments/frame/client.tsx

greater than for some reason...

Fix implementation of Measurement#less_than, which was doing

---

ts/factorio/BUILD.bazel
ts/factorio/blueprint_string.ts
ts/json.ts
ts/result.ts
ts/zod/BUILD.bazel
ts/zod/util.ts

---
* #6298
* #6297
* __->__ #6296

zemn.me: fix error safety for factorio blueprint parsing.

---

.bazelrc

Original commit changeset: be5960250c37

Back out "Fix ld on wsl2 ubuntu."

---

ts/result.ts

Better document Result.

---

pyrightconfig.json

---
* #6310
* #6309
* __->__ #6306
* #6305

Test change 2

---

README.md

---
* #6314
* #6313
* #6310
* #6309
* #6311
* __->__ #6305

Test change 1

---

README.md
pyrightconfig.json

Original commit changeset: 1ec3fcb3d01b
---
* #6314
* #6313
* #6310
* __->__ #6309
* #6311

Back out "Test change 1"

---

sh/bin/README.md

---
* #6314
* __->__ #6313
* #6310

test change

---

pyrightconfig.json
sh/bin/README.md

Original commit changeset: 093e908964f9
---
* #6314
* #6313
* __->__ #6310

Back out "Test change 2"

---

sh/bin/README.md

Original commit changeset: 6942337f1748

Back out "test change"

---

project/zemn.me/app/experiments/frame/client.tsx
ts/factorio/blueprint_book.ts
ts/factorio/react/blueprint.tsx
ts/option/option.ts

Add display support for upgrade plannners.

---

package.json
pnpm-lock.yaml
ts/do-sync/doSync.ts
ts/do-sync/testing/doSync_test.ts
ts/factorio/blueprint_book.ts
ts/json.ts
ts/pulumi/stack.ts
ts/react/Video/video.tsx
ts/url/url_test.ts

| datasource | package           | from   | to    |
| ---------- | ----------------- | ------ | ----- |
| npm        | typescript-eslint | 7.18.0 | 8.2.0 |

fix(deps): update dependency typescript-eslint to v8

---

.vscode/tasks.json

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/6398).
* #6401
* __->__ #6398

Make venv background task follow correct background task format.

---

BUILD.bazel
go/gazelle/venv/package.go
py/hello_world/BUILD.bazel
py/hello_world/__main__.py
py/sectxt/__main__.py

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/6402).
* #6404
* __->__ #6402

Make gazelle not crash when filling in the venv for a new BUILD.bazel

---

bzl/deps.bzl
cargo-bazel-lock.json
rs/cmd/sha256/main.rs
rs/ts/cmd/extract_imports/main.rs

| datasource      | package               | from   | to     |
| --------------- | --------------------- | ------ | ------ |
| github-releases | bazelbuild/rules_rust | 0.40.0 | 0.49.3 |

chore(deps): update dependency rules_rust to v0.49.3

---

BUILD.bazel
eslint.config.js

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/6480).
* #6481
* __->__ #6480

eslint: use gitignore

---

pnpm-lock.yaml
ts/math/canvas/braille/BUILD.bazel
ts/math/canvas/braille/raster_test.ts
ts/math/raster.ts

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zemn-me/monorepo/pull/6547).
* __->__ #6547
* #6546

Add bresenham's algorithm.

---

renovate.json

https://docs.renovatebot.com/configuration-options/#fetchchangelogs

Make renovate display changelogs:

---

renovate.json

Back out "Stop pinging people who make changes"
Original commit changeset: 231e55f67ee7

bring back commit links but dont linkify

---

go/cmd/doorperson/BUILD.bazel
go/cmd/doorperson/main.go

Use the openai openapi spec for the session update.

---

go/cmd/doorperson/main.go

Project doorperson: use proper realtime event response objects.

---

go/cmd/doorperson/main.go

doorperson: Use proper model for realtime buffer append

---

go/cmd/doorperson/main.go

doorperson: Add transcript

---

ts/pulumi/lulu.computer/app/client.tsx

lulu.computer: have the sharks chase the fish.

---

.vscode/tasks.json
go.sum
py/ci/postUpgrade/__main__.py
renovate.json
sh/bin/bazel

1. Add a bazelisk script to sh/bin -- it pulls it from one of several sources.
2. Alias sh/bin/bazel to it
3. Use for renovate
---
* #7108
* __->__ #7107

Fix renovate:

---

renovate.json

Original commit changeset: 46c62ff68db3

Back out "Add -- to npx --yes"

---

.github/workflows/renovate.yml

related to: https://github.com/containerbase/base/issues/3590

Try to fix renovate by pinning to an older image version.

---

project/cultist/action.ts
project/cultist/action_test.ts
project/cultist/element_test.ts
project/cultist/state/deserialize.ts
project/cultist/state/op.ts
project/cultist/state/state.ts
project/zemn.me/components/timeline/timeline.tsx

This should allow https://github.com/zemn-me/monorepo/pull/7049 to merge.

Always import immutable via import * directives

---

BUILD.bazel
ci/presubmit.ts

Remove vestigial gazelle update repos ci step.

Remove vestigial gazelle update repos ci step.

---

ts/pulumi/baby.computer/index.ts
ts/pulumi/lib/bluesky_username_claim.ts

BlueSky claim for baby.computer

BlueSky claim for baby.computer

---

project/zemn.me/app/page.tsx
project/zemn.me/app/schema.ts
project/zemn.me/bio/schema.ts

https://developers.google.com/search/docs/appearance/structured-data/profile-page#structured-data-type-definitions

Schema: follow Google's format.

---

ts/next.js/index.tsx

Disable trusted types for a bit.
